openforis/arena

common/survey/nodeDef.js, server/nodeDef/nodeDefExpressionsValidator.js, server/nodeDef/nodeDefValidator.js, webapp/appModules/surveyForm/nodeDefEdit/advanced/advancedProps.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefBoolean.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefCodeCheckbox.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefCodeDropdown.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefCoordinate.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefFile.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefTaxon.js, webapp/appModules/surveyForm/nodeDefs/components/types/nodeDefText.js, webapp/appModules/surveyForm/nodeDefs/nodeDefSwitch.js, webapp/commonComponents/tooltip.scss
=> nodeDef: add readOnly checkbox

server/record/update/thread/helpers/dependentNodesUpdater.js
when default value was applied, and default expression has been deleted, delete also node value
=> Survey publish

webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/types/nodeDefEntityForm.js
=> avoid dispatching reactGridLayout.onLayoutChange when switching form page

doc/uml/sequence/recordUpdateThread.puml, server/modules/record/manager/_internal/nodeUpdateDependentManager.js, server/modules/record/recordExprParser.js, server/modules/record/validator/validators/attributeValidator.js
code refactor, implement RecordExprParser.evalApplicableExpression and RecordExprParser.evalApplicableExpressions
=> code refactor, implement RecordExprParser.evalApplicableExpression

server/modules/collectImport/service/collectImport/metaImportJobs/categoriesImportJob.js, server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob.js
=> support 'qualifiable' code list items during Collect survey import

webapp/loggedin/modules/data/dataVis/dataQuery/dataQueryView.js, webapp/loggedin/surveyViews/nodeDefsSelector/components/attributesSelector.js, webapp/loggedin/surveyViews/nodeDefsSelector/nodeDefsSelectorView.js
…lection of single attributes only in dataQuery
=> Allow selection of single attributes only in dataQuery

server/modules/record/manager/recordManager.js, server/modules/record/repository/nodeRepository.js, server/modules/record/service/recordsUniquenessValidationJob.js, server/modules/surveyRdb/dbActions/dataTableRepository.js
=> Fixed RecordUniquenessCheckJob bug

core/record/_record/recordReader.js, core/record/_recordValidator/attributeKeyValidator.js, core/record/_recordValidator/attributeValidator.js, core/record/record.js, server/modules/record/manager/_recordManager/nodeUpdateManager.js, test/it/008recordValidationTest.js
=> EntityKeyValidator: fixed bug, nodes not validated on sibling entity delete

core/i18n/resources/en.js, webapp/loggedin/modules/home/dashboard/activityLog/activityLog.js, webapp/loggedin/modules/home/dashboard/activityLog/activityLog.scss, webapp/loggedin/modules/home/dashboard/dashboardView.js, webapp/loggedin/modules/home/dashboard/dashboardView.scss, webapp/style/_vars.scss, webapp/style/formBase.scss
This pull request is just to create the layout for the activity log to be displayed in the home page
=> Activity log layout

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob.js, server/modules/surveyRdb/schemaRdb/dataColProps.js, server/modules/user/api/userApi.js
=> Small fixes

server/db/migration/public/migrations/sqls/20180709092931-create-user-table-up.sql, server/db/migration/public/migrations/sqls/20180726092435-create-survey-def-tables-up.sql, server/db/migration/public/migrations/sqls/20181130124534-create-auth-tables-up.sql, server/db/migration/survey/migrations/sqls/20180814141148-create-record-tables-up.sql, server/db/migration/survey/migrations/sqls/20180914073047-create-category-tables-up.sql, server/db/migration/survey/migrations/sqls/20181004072545-create-taxonomy-tables-up.sql, server/db/migration/survey/migrations/sqls/20181204101541-create-history-log-table-up.sql, server/db/migration/survey/migrations/sqls/20181204141100-create-file-table-up.sql, server/db/migration/survey/migrations/sqls/20190315100007-add-table-collect-import-report-up.sql, server/db/migration/survey/migrations/sqls/20191004132253-create-analysis-table-up.sql, server/modules/auth/manager/authManager.js, server/modules/collectImport/service/collectImport/dataImportJobs/recordsImportJob.js, server/modules/record/repository/nodeRepository.js, server/modules/surveyRdb/repository/dataViewCreateRepository.js
- Most columns are now NOT NULL
- Explicitly define NULL-able columns
- Switch to GENERATED AS IDENTITY in favor of serial types
=> Refactor SQL DDL

common/surveyRdb/nodeAnalysisTable.js, server/db/migration/survey/migrations/sqls/20180814141148-create-record-tables-up.sql, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/repository/dataViewCreateRepository.js, server/modules/surveyRdb/repository/nodeAnalysisTableRepository.js, server/modules/surveyRdb/schemaRdb/dataView.js, server/modules/surveyRdb/service/surveyRdbGeneratorJob.js
added node_analysis to data schema
join node_analysis table in entity views
=> Processing chain system scripts

webapp/app/appModules.js, webapp/loggedin/modules/analysis/analysisView.js, webapp/loggedin/surveyViews/categories/categoriesView.js, webapp/loggedin/surveyViews/category/actions.js, webapp/loggedin/surveyViews/categorySelector/categorySelector.js, webapp/loggedin/surveyViews/nodeDef/basic/codeProps.js
Solved bug blank page shown after adding/editing category for analysis nodeDef.
Added categories module and category module in analysis modules to avoid node defs reload
=> NodeDefView blank page bug

.env.template, core/processUtils.js, server/db/migration/migrationConfig.js
Extract db connection parameters from DATABASE_URL environment variable (if provided)
=> DB connection: use DATABASE_URL environment variable (if provided)

common/analysis/processingStepCalculation.js, common/surveyRdb/entityAggregatedView.js, common/surveyRdb/resultStepView.js, server/modules/analysis/manager/processingChainManager.js, server/modules/surveyRdb/manager/surveyRdbManager.js, test/it/009analysisTest.js, test/it/analysisTest/complexProcessingChainTest.js, test/it/analysisTest/simpleProcessingChainTest.js, test/it/utils/chainBuilder.js, test/it/utils/surveyBuilder.js
=> Processing chain aggregation: added test cases and entity aggregated view model

.env.template, README.md, core/i18n/resources/en.js, core/processUtils.js, infra/nginx/nginx.conf, infra/nginx/rstudio_pass, infra/web/Dockerfile, infra/web/start.sh, server/modules/analysis/api/processingChainApi.js, server/modules/analysis/service/_rChain/rChain.js, server/system/appCluster.js, webapp/app/appModules.js, webapp/loggedin/modules/analysis/analysisView.js, webapp/loggedin/modules/analysis/processingChain/actions.js, webapp/loggedin/modules/analysis/processingChain/processingChainView.js, webapp/loggedin/modules/analysis/rStudio/rStudioView.js, yarn.lock
=> Rstudio server setup

README.md, server/modules/analysis/api/processingChainApi.js, server/modules/analysis/service/_rChain/_files/system/init-api.R, server/modules/analysis/service/_rChain/_files/system/init-packages.R, server/modules/analysis/service/_rChain/_files/system/init.R, server/modules/analysis/service/_rChain/_files/system/rFileInit.js, server/modules/analysis/service/_rChain/_files/system/rFileInitApi.js, server/modules/analysis/service/_rChain/_files/system/rFileInitPackages.js, server/modules/analysis/service/_rChain/_files/system/rFileLogin.js, server/modules/analysis/service/_rChain/rChain.js, server/modules/analysis/service/_rChain/rFile.js, server/modules/analysis/service/processingChainService.js
=> Processing chain: added init-api.R file to chain scripts

server/modules/user/manager/userManager.js, server/modules/user/repository/userResetPasswordRepository.js
=> User invitation expired: fixed unable to invite again users with expired invitation

server/modules/survey/manager/surveyManager.js
=> Fixed error deleting survey

webapp/loggedin/surveyViews/surveyForm/reducer.js, webapp/loggedin/surveyViews/surveyForm/surveyFormState.js
Fixes #645 
Active page not modified on node def creation but only when node def is saved.
=> Fixed blank screen shown when canceling node def page creation

core/user/_user/userPrefs.js
=> Current survey update: update user prefs on update

core/i18n/resources/en.js, webapp/loggedin/surveyViews/category/actions.js, webapp/loggedin/surveyViews/category/components/itemEdit.js
=> Category item delete: improved delete confirm message

common/apiRoutes/index.js, common/apiRoutes/rChain.js, common/apiRoutes/survey.js, core/promiseUtils.js, server/modules/analysis/api/rChainApi.js, server/modules/analysis/manager/rChainManager.js, server/modules/analysis/repository/rChainRepository.js, server/modules/analysis/service/rChainService/index.js, server/modules/analysis/service/rChainService/rFile/system/init-api.R, server/modules/analysis/service/rChainService/rFile/system/rFileInit.js, server/modules/analysis/service/rChainService/rFile/system/rFileReadData.js, server/modules/analysis/service/rChainService/rFile/system/rFileResetResults.js, server/modules/analysis/service/rChainService/rFunctions/arenaApi.js, server/modules/analysis/service/rChainService/rFunctions/index.js
=> rChain: implemented reset results api

webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/nodeDeleteButton.js, webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/types/nodeDefEntityTableRows.js
=> NodeDefEntityTable: hide output variables

webapp/loggedin/surveyViews/category/categoryState.js, webapp/loggedin/surveyViews/category/reducer.js
=> Fixed category items not persisted correctly

core/objectUtils.js, core/survey/nodeDef.js, server/db/migration/survey/migrations/sqls/20181204101541-create-history-log-table-up.sql, server/modules/activityLog/api/activityLogApi.js, server/modules/activityLog/manager/activityLogManager.js, server/modules/activityLog/repository/activityLogRepository.js, webapp/loggedin/modules/home/dashboard/activityLog/actions.js, webapp/loggedin/modules/home/dashboard/activityLog/activityLogState.js, webapp/loggedin/modules/home/dashboard/activityLog/activityLogView.js, webapp/loggedin/modules/home/dashboard/activityLog/reducer.js
=> Fixed recent activities loading

server/modules/category/categoryValidator.js
=> Fixed category validation not showing up

webapp/survey/nodeDefs/actions.js
=> Fixed NodeDefEditCode displayAs update

core/survey/nodeDefLayout.js, webapp/survey/nodeDefs/actions.js
=> NodeDefEdit: fixed update layout on 'multiple' update

webapp/guest/forgotPassword/forgotPasswordView.js
=> ForgotPasswordView: hide error message on unmount

webapp/loggedin/modules/users/user/components/profilePictureEditor.js, webapp/loggedin/modules/users/user/useUserViewState.js, webapp/loggedin/modules/users/user/userView.js
=> Fixed user edit bugs

server/modules/analysis/service/rChainService/rChain.js
=> RChain: init steps using PromiseUtils.each (order matters)

server/modules/analysis/service/rChainService/rFile/system/rFileInit.js, server/modules/analysis/service/rChainService/rStep.js
=> RSteps init calculations: use PromiseUtils.each (order matters)

core/survey/nodeDef.js, webapp/survey/nodeDefs/nodeDefsState.js
=> Fixed canceling virtual entity creation issue

server/modules/surveyRdb/repository/resultStep/create.js
=> ResultStepView: converted attribute columns to their primitive type

webapp/loggedin/surveyViews/surveyForm/nodeDefs/nodeDefUIProps.js
Fixes #746 
Integer: use 123
Decimal: use 1.23
=> NodeDef number icons

server/modules/analysis/service/rChainService/rChain.js, server/modules/analysis/service/rChainService/rFile/system/dfResults.js, server/modules/analysis/service/rChainService/rFile/system/index.js, server/modules/analysis/service/rChainService/rFile/system/listCategories.js, server/modules/analysis/service/rChainService/rFile/system/rFileReadCategories.js, server/modules/analysis/service/rChainService/rFile/system/rFileReadData.js, server/modules/analysis/service/rChainService/rFunctions/index.js, server/modules/analysis/service/rChainService/rFunctions/utility.js
=> RChain: store categories in one variable

webapp/loggedin/modules/users/user/actions.js
=> UserView: fixed error editing user when there are no surveys

server/modules/nodeDef/repository/nodeDefRepository.js, webapp/loggedin/modules/analysis/analysisView.js
Fixes #785 
Updated functions in NodeDefRepository: insertNodeDef and updateNodeDefProps
=> Chain: mark added attributes or virtual entities as draft

server/modules/surveyRdb/api/surveyRdbApi.js, webapp/commonComponents/form/downloadButton.js, webapp/loggedin/modules/data/dataVis/dataQuery/components/tableHeader/buttonDownload.js
=> DataVis: fixed error exporting data when filter contains AND clause

core/numberUtils.js, package.json, webapp/loggedin/modules/data/dataVis/dataQuery/components/tableContent/tableColumn.js, yarn.lock
=> DataVis: round decimal values to 2 decimal digits

core/i18n/resources/en.js, webapp/commonComponents/expression/expressionEditorPopupState.js, webapp/commonComponents/expression/expressionVariables.js, webapp/loggedin/modules/data/dataVis/dataQuery/components/sort/sortEditor.js, webapp/loggedin/modules/data/dataVis/dataQuery/components/sort/useSortEditorState.js
=> Expression editor improvements

server/modules/surveyRdb/api/surveyRdbApi.js, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/repository/dataView/index.js, server/modules/surveyRdb/repository/dataView/readAgg.js, server/modules/surveyRdb/service/surveyRdbService.js, server/utils/request.js
=> DataQuery: added data query aggregate endpoint

.eslintrc, core/record/recordExpressionParser.js, test/it/008recordValidationTest.js
=> RecordValidator: fixed error referencing attribute of ancestor in validation expression

webapp/loggedin/surveyViews/nodeDef/basic/basicProps.js, webapp/loggedin/surveyViews/nodeDef/nodeDefView.js, webapp/loggedin/surveyViews/nodeDef/nodeDefView.scss
=> NodeDefView: make name and type always visible

doc/reduxStore.md, webapp/app/actions.js, webapp/app/appState.js, webapp/app/reducer.js, webapp/loggedin/appHeader/appHeader.js, webapp/loggedin/modules/analysis/chain/actions/delete.js, webapp/loggedin/modules/analysis/chain/actions/persist.js, webapp/loggedin/modules/analysis/chain/actions/read.js, webapp/loggedin/modules/analysis/chain/actions/state.js, webapp/loggedin/modules/analysis/step/actions/delete.js, webapp/loggedin/modules/data/dataVis/dataQuery/actions/updateNode.js, webapp/loggedin/modules/data/dataVis/dataQuery/components/useTableState.js, webapp/loggedin/surveyViews/category/actions.js, webapp/loggedin/surveyViews/record/actions.js, webapp/store/app/index.js, webapp/store/app/reducer.js, webapp/store/app/saving/actions.js, webapp/store/app/saving/hooks.js, webapp/store/app/saving/index.js, webapp/store/app/saving/reducer.js, webapp/store/app/saving/state.js
- AppSaving store refactor
- **[Added Redux store doc](https://github.com/openforis/arena/pull/858/files#diff-dedbad1c381d2b0b32d702b036888056)**
=> Refactored AppSaving store

common/model/db/sql/index.js, common/model/db/tables/dataNodeDef/table.js, common/model/db/tables/table.js, common/model/db/views/dataNodeDef/view.js, common/surveyRdb/nodeDefTable.js, server/modules/surveyRdb/repository/dataView/create.js
=> Fixed error generating RDB when survey has multiple attributes

webapp/components/DataQuery/ButtonBar/ButtonBar.js, webapp/components/DataQuery/ButtonBar/ButtonFilter/ButtonFilter.js, webapp/components/DataQuery/ButtonBar/ButtonSort/ButtonSort.js, webapp/components/DataQuery/ButtonBar/store/index.js, webapp/components/DataQuery/ButtonBar/store/state/index.js, webapp/components/DataQuery/ButtonBar/store/state/state.js, webapp/components/DataQuery/ButtonBar/store/useButtonBar.js
=> DataQuery ButtonBar: added local store to handle panels

server/modules/analysis/service/rChain/rChain.js, server/modules/category/api/categoryApi.js, server/modules/category/manager/categoryManager.js, server/modules/category/repository/categoryRepository.js, server/modules/category/service/categoryService.js, server/modules/survey/service/publish/jobs/categoriesValidationJob.js, test/2_integration/surveyTests/categoryTest.js
This pull request is part of a bigger pull request.
It won't be merged directly into master branch.
=> Refactored Categories API: updated endpoint to match Table format

server/modules/taxonomy/api/taxonomyApi.js, server/modules/taxonomy/manager/taxonomyManager.js, server/modules/taxonomy/repository/taxonomyRepository.js, webapp/components/survey/NodeDefDetails/TaxonProps.js
=> make endpoint

core/arena/identity.js, core/arena/index.js, webapp/components/form/Dropdown/Dropdown.js, webapp/components/form/Dropdown/ItemDialog/ItemDialog.js, webapp/components/survey/CategoryDetails/CategoryDetails.js, webapp/components/survey/CategoryDetails/ImportSummary/ImportSummary.js, webapp/components/survey/CategoryDetails/ImportSummary/TableRow.js, webapp/components/survey/CategoryDetails/store/actions/index.js, webapp/components/survey/CategoryDetails/store/actions/useHideImportSummary.js, webapp/components/survey/CategoryDetails/store/actions/useImportCategory.js, webapp/components/survey/CategoryDetails/store/actions/useImportSummary.js, webapp/components/survey/CategoryDetails/store/actions/useSetImportSummaryColumnDataType.js, webapp/components/survey/CategoryDetails/store/actions/useUploadCategory.js, webapp/components/survey/CategoryDetails/store/state/state.js
Note: there are still some TODOs that will be addressed in the next pull request (category levels edit)
=> Refactor Category : import category

webapp/loggedin/surveyViews/surveyForm/surveyFormView.scss
=> SurveyForm: show items resize icon only in edit mode

webapp/views/App/views/Analysis/Chain/store/actions/useSave.js
=> After save chain leave calculation and steps openned

webapp/views/App/JobMonitor/InnerJobs/InnerJob/InnerJob.js, webapp/views/App/JobMonitor/InnerJobs/InnerJob/index.js, webapp/views/App/JobMonitor/InnerJobs/InnerJobs.js
=> autoscroll to job running

webapp/components/survey/NodeDefDetails/NodeDefDetails.js, webapp/components/survey/SurveyForm/nodeDefs/nodeDefUIProps.js
=> remove validations on nodedef edit

core/validation/validation.js, server/modules/survey/service/recordCheckJob.js, server/modules/surveyRdb/service/surveyRdbCreationJob/recordsUniquenessValidationJob.js
=> Bugfix - record keys uniqueness validation

server/modules/record/manager/_recordManager/nodeUpdateManager.js, webapp/components/form/InputChips/store/actions/useOnDropdownChange.js, webapp/components/form/InputChips/store/actions/useRemoveItem.js
Fixes #1055 
In NodeUpdateManager the main change is in lines 50 to 60; other changes have been done only to avoid ESLint errors.
=> Bugfix - error editing node def code with parent code specified

webapp/store/ui/surveyForm/actions.js
=> NodeDefEntityFormNodeSelect: showing proper label for code and taxon key attributes

core/record/recordExpressionParser.js, webapp/components/expression/nodes/binaryOperand.js, webapp/components/expression/nodes/expressionNode.js, webapp/components/expression/nodes/literal.js
=> Relevant if expression: fixed expression evaluation using constant value

webapp/app/appErrorsMiddleware.js, webapp/components/hooks/useRequest.js, webapp/components/survey/CategoryDetails/store/actions/item/useFetchLevelItems.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCode.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/store/hooks/index.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/store/hooks/useItems.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/store/index.js, webapp/service/api/categories/index.js
Fixes #1079
Main changes are in NodeDefCode.
A hook like useFetchItems or something similar could be introduced to move some of the code there.
=> Attempt to solve issue with node def code items fetching

core/survey/collectImportReportItem.js, server/modules/collectImport/api/collectImportApi.js, server/modules/collectImport/repository/collectImportReportRepository.js
=> Collect import report: added node def name column to CSV export

core/record/recordExpressionParser.js
=> Relevant if expression: fixed error cannot find node

core/expressionParser/expression.js
=> change regex to find long chains of = symbol

webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCode.scss
=> dropdown 100% width

server/utils/webSocket.js, webapp/components/survey/Record/store/useLocalState.js
=> Record: checkout record on unmount

core/geo/point.js, server/modules/collectImport/service/collectImport/metaImportJobs/samplingPointDataImportJob.js, server/modules/surveyRdb/schemaRdb/dataColProps.js
=> Geometry point: improved parsing function

core/i18n/resources/en.js, core/validation/_validator/validatorErrorKeys.js, server/modules/taxonomy/taxonomyValidator.js
=> Taxonomy import: avoid duplicate vernacular names for the same language

core/record/_recordValidator/countValidator.js, webapp/components/survey/SurveyForm/nodeDefs/components/useValidation.js
Fixes #1134 
The change that fixes the issue is only in the file webapp/components/survey/SurveyForm/nodeDefs/components/useValidation.js line 31.
The other changes have been done only to avoid ESLint errors.
=> Fixed min/max count errors not shown in code attributes

common/analysis/processingStep.js, webapp/views/App/views/Analysis/Chain/ButtonBar/ButtonBar.js, webapp/views/App/views/Analysis/Chain/store/actions/useSave.js, webapp/views/App/views/Analysis/Chain/store/state/state.js
=> Fixed processing chain could not be saved after analysis attribute creation

test/e2e/tests/006-surveyFormEditTree.js
=> fix 006 test

server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js
=> nodeUpdateDependentManager: fix read only values not being updated

test/e2e/tests/007-surveyFormEditPlotCode.js, test/e2e/tests/009-surveyFormEditPlotCodeChildren.js, test/e2e/utils/api/browser.js, test/e2e/utils/api/index.js, test/e2e/utils/ui/nodeDefDetail.js, test/e2e/utils/ui/surveyForm.js
=> Test - Plot add code attribute children

core/survey/nodeDefLayout.js, test/e2e/tests/004-surveyFormEditCluster.js, test/e2e/tests/005-surveyFormEditPlot.js, test/e2e/tests/006-surveyFormEditTree.js, test/e2e/tests/007-surveyFormEditPlotCode.js, test/e2e/tests/009-surveyFormEditPlotCodeChildren.js, test/e2e/tests/010-surveyFormEditTreeTaxon.js, test/e2e/utils/ui/nodeDefDetail.js, test/e2e/utils/ui/surveyForm.js, test/e2e/utils/ui/taxonomyDetails.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityFormGrid.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntitySwitch.js
=> Test SurveyEdit - Tree: add attribute type Taxon

server/modules/surveyRdb/repository/dataTableUpdateRepository.js, server/modules/surveyRdb/repository/dataView/read.js
=> Solved error creating record

server/modules/collectImport/service/collectImport/dataImportJobs/recordsImportJob.js, webapp/views/App/views/Analysis/Chain/store/actions/step/useUpdateProps.js
=> place to do the change

common/model/db/tables/dataNodeDef/table.js, common/model/db/views/dataNodeDef/view.js, core/record/nodeKeys.js, server/modules/record/repository/validationReportRepository.js, server/modules/surveyRdb/repository/dataView/create.js, server/modules/surveyRdb/repository/nodeHierarchyDisaggregatedViewRepository.js, server/modules/surveyRdb/repository/nodeKeysHierarchyViewRepository.js, server/modules/surveyRdb/repository/nodeKeysViewRepository.js, server/modules/surveyRdb/schemaRdb/nodeHierarchyDisaggregatedView.js, server/modules/surveyRdb/schemaRdb/nodeKeysHierarchyView.js, server/modules/surveyRdb/schemaRdb/nodeKeysView.js
=> Fixed data validation report blank (request timeout) - improved query

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntitySwitch.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntitySwitch.scss
=> Fixed multiple entity with table layout not showing properly in its own page

core/survey/_surveyValidator/nodeDefExpressionsValidator.js
=> Fixed validation of expressions using attributes inside single entities

webapp/components/PanelRight/PanelRight.js, webapp/components/PanelRight/panelRight.scss, webapp/components/form/Input/Input.js
=> title and expanded panel right

core/record/recordExpressionParser.js
=> Expression parser: fixed evaluation of attributes inside single entities

webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js, webapp/views/App/views/Designer/SurveyHierarchy/Tree/Tree.js
=> change hierarchy label

webapp/components/Table/Header/Header.js
=> Paginator: replace current entry in history stack when changing page

.travis.yml
=> deploy to dev on master push

server/modules/nodeDef/manager/layout/NodeDefLayoutManager.js
=> Fixed extra space added between attributes when importing Collect survey

webapp/service/storage/explorer/storage.js
=> Data Explorer: fixed error navigating to record edit, then going back to explorer view

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableCell.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableRow.js
=> Multiple entity with table layout: fixed error dragging row while entering data

core/i18n/resources/en.js, core/survey/category.js, server/modules/category/repository/categoryRepository.js, webapp/components/survey/CategoryList/CategoryList.js, webapp/components/survey/CategoryList/TableRow/TableRow.js, webapp/components/survey/CategoryList/TableRowHeader/TableRowHeader.js
=> Category list: show category type (flat/hierarchical)

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefBoolean.scss
=> Fixed node def boolean error icon covering buttons

webapp/components/survey/SurveyForm/components/FormPageNavigation/store/state/state.js, webapp/components/survey/SurveyForm/components/FormPageNavigation/store/useLocalState.js
=> 1237-remove-subpage-breaks-editor

server/utils/webSocket.js
=> WebSocket: use socket client ID to index sockets

server/utils/request.js, server/utils/webSocket.js, webapp/app/appWebSocket.js
=> WebSockets: pass socket id in request headers

server/modules/taxonomy/manager/taxonomyImportManager.js, server/modules/taxonomy/service/taxonCSVParser.js, server/modules/taxonomy/service/taxonomyImportJob.js, test/e2e/resources/taxonomies/species list valid (without family and genus).csv, test/e2e/tests/011-taxonomyDetailsEditTaxonomy.js, webapp/components/survey/TaxonomyDetails/TaxonomyDetails.scss
=> Taxonomy import without family

core/geo/srs.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefCoordinate.js, webapp/views/App/views/Home/SurveyInfo/SrsEditor/SrsEditor.js
=> NodeDefCoordinate: show name and code in SRS selector

webapp/components/expression/expressionVariables.js
=> Bugfix / expression variables duplicates

webapp/components/expression/advancedExpressionEditorPopup.js, webapp/components/expression/codemirrorArenaExpressionHint.js
=> Expression editor: variables not visible in advanced mode

webapp/components/hooks/index.js, webapp/components/hooks/useQuery.js, webapp/components/survey/Record/store/useLocalState.js
=> Validation Reports - Fix links

server/modules/record/api/recordApi.js, server/modules/surveyRdb/repository/nodeKeysHierarchyViewRepository.js
=> fix validation report paths

webapp/components/expression/advancedExpressionEditorPopup.js, webapp/components/expression/expressionEditor.js, webapp/components/expression/expressionEditorPopup.js, webapp/components/survey/NodeDefDetails/ExpressionsProp/ExpressionProp.js, webapp/components/survey/NodeDefDetails/ExpressionsProp/ExpressionsProp.js, webapp/components/survey/NodeDefDetails/ValidationsProps.js
=> NodeDef Validations: allow advanced expression editor and include current node def

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob.js, server/modules/nodeDef/manager/nodeDefManager.js, server/modules/survey/manager/surveyManager.js
=> Fixed error importing survey from Collect

webapp/components/form/DateInput/ReactDateInput/reactDateInput.scss
=> avoid date cut

test/e2e/resources/nodeDefs/nodeDefs.js, test/e2e/resources/records/recordsData.js, test/e2e/tests/018-surveyExport.js, test/e2e/utils/PromiseUtils.js, test/e2e/utils/surveyExport/activityLog.js, test/e2e/utils/surveyExport/categories.js, test/e2e/utils/surveyExport/chains.js, test/e2e/utils/surveyExport/extract.js, test/e2e/utils/surveyExport/nodeDefs.js, test/e2e/utils/surveyExport/records.js, test/e2e/utils/surveyExport/survey.js, test/e2e/utils/surveyExport/taxonomies.js, test/e2e/utils/surveyExport/users.js
Resolves remove root imputs
extract some methods and remove imports that required some package into @XXX
Tests e2e
Tests are working
=> remove root imports e2e

test/unit/tests/002recordExpressionParser.test.js
Quick fix of a unit test that fails frequently in GitHub actions.
Nothing to say.
=> Fixed Date functions unit tests failing

server/modules/survey/service/clone/jobs/CloneTablesJob.js, test/e2e/tests/surveyClone.js, webapp/views/App/views/Home/Dashboard/ActivityLog/ActivityLog.js
Resolves #1428 
Add activity log create on cloned survey
=> show log on activity log

test/e2e/tests/nodeDefReorder.js, test/e2e/tests/utils/dragDrop.js
Resolves #1397 
Into `webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableCell.js` we can see that the cells had the onMouseDown stopped ✋.
The DnD is managed by 3 functions into `webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableRow.js`
the dragOver function takes the mouse position created by the synthetic event, 
The solution proposed is to dispatch the drag and drop events using the function dragAndDropOver.
No changes
This can also happen in the CalculationList
=> reorder entity table

common/model/db/tables/node/select.js, core/expressionParser/helpers/functionImplementations.js, core/expressionParser/helpers/functions.js, core/record/node.js, core/record/recordExpressionParser/recordEpressionFunctions.js, core/record/recordExpressionValueConverter.js, core/survey/_survey/surveyCategories.js, core/survey/_survey/surveyRefDataIndex.js, core/survey/survey.js, server/modules/collectImport/service/collectImport/dataImportJobs/collectAttributeValueExtractor.js, server/modules/record/service/update/thread/recordUpdateThread.js, server/modules/survey/manager/surveyManager.js, test/unit/tests/002recordExpressionParser.test.js, test/utils/dataTest/dataTest.js, test/utils/surveyBuilder/categoryBuilder.js, test/utils/surveyBuilder/categoryItemBuilder.js, test/utils/surveyBuilder/index.js, test/utils/surveyBuilder/taxonBuilder.js, test/utils/surveyBuilder/taxonomyBuilder.js, webapp/components/expression/codemirrorArenaExpressionHint.js
Added categoryItemProp function to custom functions in record expression evaluator.
Unit tests have been added,
Validation of expressions using this function can be improved (e.g. check that the specified categoryName or propName exist)
=> Expression functions: categoryItemProp

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/nodeDefsImportJob.js
Resolves #1308
In the NodeDefImportJob, description elements are converted into "labels" and associated to the node def props descriptions field.
Tests have been done only locally.
=> Collect import: fixed node def tooltips imported as descriptions

server/modules/arenaImport/service/arenaImport/metaImportJobs/categoriesImportJob.js, server/modules/category/manager/categoryManager.js, server/modules/category/repository/categoryRepository.js
Fixed error importing survey from Collect (wrong parameters passed to insertItems function in categoryRepository.js).
Tested importing a template survey generated from Collect (no matter about the survey, every Collect survey import was crashing).
=> Fixed error importing survey from Collect (CategoriesImportJob)

server/modules/analysis/repository/chainNodeDef/index.js, server/modules/analysis/repository/chainNodeDef/insert.js, server/modules/analysis/repository/chainNodeDefAggregate/index.js, server/modules/arenaImport/service/arenaImport/arenaImportJob.js, server/modules/arenaImport/service/arenaImport/metaImportJobs/chainsImportJob.js, server/modules/arenaImport/service/arenaImport/model/arenaSurveyFileZip.js
=> Cu j76v9v analysis survey import ramirobgav

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/collectExpressionConverter.js, server/utils/response.js, test/unit/tests/008CollectExpressionConverter.test.js
=> Bugfix / Collect survey export/import

core/record/_record/recordReader.js, core/record/_recordValidator/attributeValidator.js, core/record/_recordValidator/countValidator.js, core/record/record.js, server/modules/survey/service/recordCheckJob.js
=> improved RecordCheckJob speed

core/record/_record/recordReader.js
=> fixed child nodes sorting

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/nodeDefsImportJob.js
=> fixed Collect import null values in labels

server/modules/arenaImport/service/arenaImport/metaImportJobs/categoriesImportJob.js, server/modules/arenaImport/service/arenaImport/metaImportJobs/taxonomiesImportJob.js, server/modules/survey/api/surveyApi.js, server/modules/survey/repository/surveyRepository.js, webapp/components/Table/Content/Content.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTree.scss
=> fixed error importing surveys from Arena

common/model/db/tables/dataNodeDef/columnNodeDef.js, common/surveyRdb/nodeDefTable.js, core/survey/nodeDef.js, server/db/dbUtils.js, server/modules/analysis/api/rChainApi.js, server/modules/analysis/service/rChain/index.js, server/modules/analysis/service/rChain/rFile/system/dfResults.js, server/modules/analysis/service/rChain/rFile/system/rFileReadData.js, server/modules/nodeDef/manager/nodeDefManager.js, server/modules/nodeDef/repository/nodeDefRepository.js, server/modules/record/repository/recordRepository.js, server/modules/surveyRdb/repository/dataTableReadRepository.js, server/modules/surveyRdb/repository/dataTableUpdateRepository.js, server/modules/surveyRdb/repository/dataView/read.js, server/modules/surveyRdb/repository/resultNode/delete.js, server/modules/surveyRdb/repository/resultNode/massiveUpdateData.js, server/modules/surveyRdb/repository/resultNode/massiveUpdateNodes.js, server/modules/surveyRdb/schemaRdb/dataCol.js, server/modules/surveyRdb/schemaRdb/dataColProps.js, server/modules/surveyRdb/schemaRdb/dataTable.js, server/modules/surveyRdb/schemaRdb/dataView.js, webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js, webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js, webapp/components/DataQuery/Visualizer/Table/Row/Column/store/useColumn.js, webapp/components/DataQuery/Visualizer/Table/store/useTable.js, webapp/components/expression/expressionVariables.js
=> Persit user script

core/i18n/resources/en.js, webapp/app/appModules.js, webapp/views/App/SideBar/Modules/ModuleLink/ModuleLink.js, webapp/views/App/SideBar/Modules/utils.js
=> added link to user manual

core/dateUtils.js, webapp/views/App/views/Data/Records/Row/Row.js
=> format key date attributes in records list

core/i18n/resources/en.js, server/modules/record/manager/fileManager.js, server/modules/record/repository/fileRepository.js, server/modules/record/service/fileService.js, server/modules/survey/service/surveyExport/jobs/filesExportJob.js
=> fixed Arena files export job

core/auth/authorizer.js, core/i18n/resources/en.js, server/modules/user/api/userApi.js, server/modules/user/service/userService.js, test/e2e/tests/_record/enterEntities.js, webapp/views/App/views/Users/DropdownUserGroup/DropdownUserGroup.js, webapp/views/App/views/Users/UserInvite/UserInvite.js, webapp/views/App/views/Users/UserInvite/store/actions/index.js, webapp/views/App/views/Users/UserInvite/store/actions/useOnInvite.js
=> User invite: show permissions

webapp/components/Table/tableLink.js
=> fixed paginator not going back to first page

server/modules/record/manager/_recordManager/nodeUpdateManager.js
=> when min count is set, create minimum amount of entities/attributes

webapp/components/expression/nodes/literal.js, webapp/components/form/DateInput/ReactDateInput/component.js, webapp/components/form/DateInput/ReactDateInput/reactDateInput.scss
=> show date input field when defining constant value of type date in basic expression editor

core/i18n/resources/en.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityForm.scss, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityFormNodeSelect.js
=> improve entity selector

package.json, yarn.lock
=> upgraded arena-core version (fixed error importing Collect survey)

webapp/views/App/Header/Header.scss
=> Show cycle

webapp/components/expression/nodes/literal.js
=> fixed cannot add constant values in expressions

core/survey/survey.js, server/modules/collectImport/service/collectImport/metaImportJobs/surveyCreatorJob.js
=> fixed srs not imported from Collect survey

server/modules/collectImport/service/collectImport/dataImportJobs/collectAttributeValueExtractor.js
=> do not import invalid time nodes

webapp/components/form/DateInput/ReactDateInput/component.js
=> close date input calendar after selection

webapp/store/user/hooks.js
=> fixed cannot demote record to undefined

server/modules/arenaImport/service/arenaImport/jobs/recordsImportJob.js, webapp/components/survey/NodeDefDetails/AnalysisProps/index.js
=> Update script when category change

webapp/components/survey/CategoryList/TableHeaderLeft/TableHeaderLeft.js, webapp/components/survey/TaxonomyList/HeaderLeft/HeaderLeft.js
=> hide category/taxonomy add buttons when user has no survey edit permission

test/e2e/tests/_record/enterAttributes.js, test/e2e/tests/surveyFormPreview.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefCoordinate.js
=> coordinate input field: select default SRS in UI when there is only one defined

server/modules/analysis/service/rChain/rFile/system/rFileReadData.js
=> avoid analysis nodes

core/i18n/resources/en.js, webapp/components/form/Dropdown/Dropdown.js, webapp/components/form/InputChips/InputChips.js, webapp/views/App/views/Home/SurveyInfo/SrsEditor/SrsEditor.js
=> added placeholder to srs editor

server/modules/record/repository/validationReportRepository.js
=> exclude analysis variables from validation report

core/survey/nodeDef.js, server/modules/nodeDef/repository/nodeDefRepository.js, server/modules/survey/service/recordCheckJob.js
=> validate only modified node defs survey publish

webapp/store/user/hooks.js
=> fixed blank screen on record delete

server/modules/survey/api/surveyApi.js, webapp/store/survey/actions/export.js
=> changed exported file name

core/i18n/resources/en.js, server/modules/collectImport/service/collectImport/dataImportJobs/recordsImportJob.js, server/modules/record/manager/_recordManager/recordUpdateManager.js, server/modules/record/manager/recordManager.js, server/modules/record/repository/recordRepository.js, webapp/views/App/views/Data/DataImport/DataImport.js
=> Data import: delete all records only in selected cycle

webapp/views/App/views/Users/UserInvite/UserInvite.js, webapp/views/App/views/Users/UserInvite/store/actions/useOnInvite.js
=> improved user invite form

webapp/components/survey/TaxonomyDetails/TaxonomyDetails.js
=> enlarged taxa table columns

webapp/components/survey/CyclesSelector/CyclesSelector.js, webapp/store/ui/chain/actions/openRStudio.js
=> add cycle key

server/modules/analysis/service/rChain/index.js, server/modules/analysis/service/rChain/rFile/system/dfResults.js, server/modules/nodeDef/manager/nodeDefManager.js, server/modules/nodeDef/repository/nodeDefRepository.js, server/modules/survey/manager/surveyManager.js
=> filter analysis variables

server/modules/record/repository/nodeRepository.js
=> fixed nodes sorting in UI

webapp/components/survey/NodeDefDetails/AnalysisEntitySelector/index.js, webapp/components/survey/NodeDefDetails/NodeDefDetails.js, webapp/components/survey/NodeDefsSelector/EntitySelector/EntitySelector.js
resolves #1820 
resolves #1819
=> lock entity

webapp/components/survey/NodeDefDetails/AnalysisProps/index.js
=> update code script

webapp/store/survey/nodeDefs/reducer.js
=> fixed node def not updated on save

core/Countries.js, core/countries_data.json, core/user/userAccessRequest.js, webapp/components/form/Input/Input.js, webapp/views/Guest/views/AccessRequest/AccessRequest.js
=> User access request: select country from dropdown

core/i18n/resources/en.js, core/record/node.js, core/survey/nodeDefLayout.js, webapp/components/buttons/Button.js, webapp/components/survey/SurveyForm/components/addNodeDefPanel.js, webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefEditButtons.js, webapp/store/survey/nodeDefs/actions.js
=> add button to compress form items

server/modules/activityLog/manager/activityLogManager.js, server/modules/activityLog/repository/activityLogRepository.js, server/modules/activityLog/service/activityLogService.js, server/modules/arenaImport/service/arenaImport/jobs/activityLogImportJob.js, server/modules/arenaImport/service/arenaImport/model/arenaSurveyFileZip.js, server/modules/record/manager/recordManager.js, server/modules/record/repository/nodeRepository.js, server/modules/record/service/recordService.js, server/modules/record/service/update/thread/recordUpdateThread.js, server/modules/survey/service/recordCheckJob.js, server/modules/survey/service/surveyExport/exportFile.js, server/modules/survey/service/surveyExport/jobs/activityLogExportJob.js, server/modules/survey/service/surveyExport/jobs/recordsExportJob.js, test/e2e/tests/_surveyExport/activityLog.js, test/e2e/tests/_surveyExport/records.js
=> Improved survey export

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefFile.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefFile.scss
=> show file preview only inside tooltip

core/record/_record/recordNodeDependentsUpdater.js
=> fixed nodes relevance not updated correctly

core/i18n/resources/en.js, webapp/components/Map/Map.js, webapp/components/Map/Map.scss, webapp/components/Map/MapMarker/MapMarker.js, webapp/components/Map/MapMarker/MapMarkerPopup.js, webapp/components/Map/MapMarker/index.js, webapp/components/Map/MapMarker/useMapMarker.js, webapp/components/Map/useMap.js, webapp/components/hooks/index.js, webapp/components/hooks/useSRSs.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefCoordinate.js, webapp/views/App/views/Data/MapView/MapView.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataClusters.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataLayer.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/useSamplingPointDataLayer.js, webapp/views/App/views/Data/MapView/useRandomColor.js
resolves #1933 
resolves #1935
=> Map view: set random colors to sampling point data layers

core/i18n/resources/en.js, server/modules/category/service/categoryService.js, webapp/components/Map/Map.scss, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataClusters.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataItemPopup.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/useSamplingPointDataLayer.js, webapp/views/App/views/Data/MapView/useRandomColor.js
=> Map view: sampling point data marker popup

.mergify.yml, core/i18n/resources/en.js, server/modules/collectImport/service/collectImport/metaImportJobs/taxonomiesImportJob.js, server/modules/taxonomy/service/taxonCSVParser.js
=> fixed Taxonomy import error messages

webapp/views/App/views/Data/Explorer/Explorer.js
=> Data Explorer: store query in local storage on location update

core/record/_record/recordNodesIndex.js, core/record/_record/recordUpdater.js, server/modules/record/manager/_recordManager/nodeUpdateManager.js, server/modules/record/manager/_recordManager/recordUpdateManager.js, server/modules/survey/service/recordCheckJob.js, test/integration/tests/004applicableUpdatetest.js, test/integration/tests/005calculatedValueUpdatetest.js, webapp/store/ui/record/state.js
=> made RecordCheckJob faster

test/e2e/tests/_formDesigner/index.js, test/e2e/tests/recordVerify.js, test/e2e/tests/validationReport.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityForm.js, webapp/store/ui/surveyForm/actions.js
=> Bugfix / form entity selector

webapp/components/DataQuery/store/useDataQuery.js
=> Data Explorer: reload table data on paginator number of rows updates

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/nodeDefsImportJob.js
=> Collect Import: mark specify field as hidden when not relevant

core/auth/authorizer.js, webapp/store/user/hooks.js, webapp/views/App/views/Home/Dashboard/SurveyInfo/SurveyInfo.js
=> survey export: allow only to survey admin and system admin

server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/collectExpressionConverter.js, test/unit/tests/008CollectExpressionConverter.test.js
=> Collect Import: fixed error converting logical epressions

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityForm.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDef/AnalysisNodeDef.scss
issue occurred with nested entities; the page of the nested one remained disabled without reason.
=> fixed page remains disabled

webapp/views/App/views/Home/CollectImportReport/CollectImportReport.scss
=> Collect import report: enlarge Expression column cells

webapp/components/DataQuery/ButtonBar/ButtonDownload/ButtonDownload.js, webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.js, webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.scss, webapp/components/survey/SurveyForm/components/formEntryActions.js, webapp/views/App/views/Designer/SurveyHierarchy/Tree/Tree.js
=> Hierarchy: show description tooltip on attribute mouse over

core/auth/authorizer.js, webapp/views/App/SideBar/Modules/utils.js
only survey editors can access form designer;
only data analyzers and above can access categories and taxonomies; 
only survey managers can access users module;
resolves #2044 
resolves #2045
=> modules accessibility

server/modules/surveyRdb/manager/surveyRdbManager.js
=> export only published nodedef properties

core/auth/authorizer.js, webapp/views/App/AppView.js, webapp/views/App/SideBar/Modules/utils.js, webapp/views/App/views/Data/Data.js, webapp/views/App/views/Designer/Designer.js
=> Prevent access to Designer and Data modules to unauthorized users

webapp/components/PanelRight/panelRight.scss
=> Fixed PanelRight button showing in the middle

webapp/store/login/actions.js, webapp/views/App/Header/UserPopupMenu/UserPopupMenu.js
=> Redirect to home page on logout

webapp/components/survey/TaxonomyDetails/TaxonomyDetails.scss
=> Taxonomy details: fixed layout messy with multiple languages

webapp/views/App/AppView.js, webapp/views/App/views/Users/Users.js
=> fixed access to User profile

core/record/record.js, server/modules/arenaImport/service/arenaImport/jobs/recordsImportJob.js, server/modules/arenaImport/service/arenaImport/jobs/usersImportJob.js, server/modules/survey/service/surveyExport/surveyExportJob.js
=> Arena survey import: allow importing survey without activity log and users

webapp/components/Map/MapBaseLayerPeriodSelector.js
=> fixed map period selector not visible

common/model/db/index.js, common/model/db/tables/dataNodeDef/columnNodeDef.js, common/model/db/views/dataNodeDef/index.js, common/model/db/views/dataNodeDef/view.js, common/model/db/views/dataNodeDef/viewColumnNodeDef.js, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/repository/dataView/create.js, server/modules/surveyRdb/repository/dataView/read.js, server/modules/surveyRdb/schemaRdb/dataColProps.js
=> Data export: include category item labels in all survey languages

LICENSE, common/model/csvExport/CsvExportModel.js, common/model/csvExport/index.js, core/i18n/resources/en.js, server/modules/category/service/categoryService.js, server/modules/collectImport/api/collectImportApi.js, server/modules/dataImport/service/DataImportTemplateService.js, server/modules/record/api/recordApi.js, server/modules/record/service/recordService.js, server/modules/survey/api/surveyApi.js, server/modules/surveyRdb/repository/dataView/read.js, server/modules/taxonomy/api/taxonomyApi.js, server/modules/user/api/userApi.js, server/utils/response.js, webapp/service/api/data/index.js, webapp/service/api/index.js, webapp/utils/testId/index.js, webapp/views/App/Header/Header.js, webapp/views/App/views/Data/DataImport/DataImport.js, webapp/views/App/views/Data/DataImport/DataImport.scss, webapp/views/App/views/Data/DataImport/DataImportCollectView.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js
download CSV data import from Data Import view
There is even a refactoring of Response.setContentTypeFile function signature that involved several files.
=> CSV data import template

common/analysis/chain.js, core/i18n/resources/en.js, webapp/components/survey/CategorySelector/CategorySelector.js, webapp/views/App/views/Analysis/Chain/Chain.scss, webapp/views/App/views/Analysis/Chain/ChainBasicProps.js, webapp/views/App/views/Analysis/Chain/ReportingDataAttributeDefs/ReportingDataAttributeDefs.js, webapp/views/App/views/Analysis/Chain/ReportingDataAttributeDefs/index.js
=> Chain: added reporting data category and attributes selection

server/modules/analysis/service/rChain/rChain.js, server/modules/analysis/service/rChain/rFile/fileChainSummaryJson.js, server/modules/analysis/service/rChain/rFile/system/init-chain.R, webapp/store/ui/chain/actions/openRStudio.js
=> Include chain summary json in RStudio files

server/modules/analysis/api/chainApi.js, server/modules/analysis/service/rChain/rChain.js, server/modules/analysis/service/rChain/rFile/fileChainSummaryJson.js, server/modules/analysis/service/read.js, webapp/views/App/views/Analysis/Chain/ButtonBar/ButtonBar.js
=> Chain summary enhancements

webapp/views/App/views/Analysis/Chain/ChainBasicProps.js, webapp/views/App/views/Analysis/Chain/ChainSamplingDesignProps.js
=> Chain: moved reporting data section to Sampling Design tab

server/modules/analysis/service/read.js
=> Chain summary reporting data category

server/modules/analysis/service/read.js
=> Chain summary: added clustering entity keys

.eslintrc, .husky/pre-commit, package.json, server/modules/analysis/service/chainSummaryGenerator.js, yarn.lock
=> Chain summary: harmonize reporting data category

webapp/components/survey/CategorySelector/CategorySelector.js, webapp/views/App/views/Analysis/Chain/ReportingDataAttributeDefs/ReportingDataAttributeDefs.js
=> Chain / reporting data: added empty selection

webapp/components/expression/advancedExpressionEditorPopup.js, webapp/components/expression/codemirrorArenaExpressionHint.js, webapp/components/expression/expressionVariables.js
=> Expressions editor: always show current variable first

core/i18n/resources/en.js
=> User access request: updated email content (link in plain text)

core/i18n/resources/en.js, webapp/views/App/views/Analysis/Chain/BaseUnitSelector/BaseUnitSelector.js
=> Chain base unit: added deletion confirm

server/modules/analysis/api/rChainApi.js
=> Chain / RStudio: added extra props to categories dataframes

core/survey/_survey/surveyDependencies.js, core/survey/survey.js, server/modules/nodeDef/api/nodeDefApi.js, server/modules/nodeDef/service/nodeDefService.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDefs.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/hooks/useSortAnalysisNodeDefs.js
=> fixed error sorting analysis variables in chain

core/survey/_survey/surveyAnalysis.js, core/survey/survey.js, server/modules/analysis/service/chainSummaryGenerator.js, webapp/views/App/views/Analysis/Chain/ChainSamplingDesignProps.js, webapp/views/App/views/Analysis/Chain/ReportingDataAttributeDefs/ReportingDataAttributeDefs.js
=> Bugfix / chain improvements

core/survey/_survey/surveyAnalysis.js, webapp/store/survey/nodeDefs/actions.js
=> show sampling node defs without siblings by default

server/modules/analysis/manager/chain/index.js
=> Chain delete: fixed mark node defs as deleted

common/analysis/areaBasedEstimatedNodeDef.js, common/analysis/chain.js, common/analysis/samplingNodeDefs.js, core/survey/_survey/surveyAnalysis.js, core/survey/_survey/surveyNodeDefs.js, core/survey/survey.js, server/modules/arenaImport/service/arenaImport/jobs/nodeDefsImportJob.js, server/modules/nodeDef/manager/nodeDefManager.js, server/modules/nodeDef/repository/nodeDefRepository.js, server/modules/nodeDef/service/nodeDefService.js, server/modules/survey/service/publish/jobs/chainSamplingNodeDefsCheckJob.js, server/modules/survey/service/publish/jobs/chainsCyclesCheckJob.js, server/modules/survey/service/publish/surveyPublishJob.js, webapp/store/survey/nodeDefs/actions.js, webapp/views/App/views/Analysis/Chain/BaseUnitSelector/BaseUnitSelector.js
=> Base unit selection

core/auth/authorizer.js, core/user/userAccessRequestAccept.js
=> user access request: survey manager as default (removed "survey administrator" option)

webapp/components/survey/SurveyForm/SurveyForm.scss
=> Form Designer: fixed show horizontal scrollbar at all time

server/modules/taxonomy/manager/taxonomyImportManager.js
=> fixed error importing taxonomy

core/validation/validation.js, server/modules/category/categoryValidator.js, webapp/components/survey/CategoryList/CategoryList.js, webapp/components/warningBadge.scss
=> Category list: do not show warnings as errors

server/modules/analysis/service/chainSummaryGenerator.js
=> Chain summary: added postStratificationCategory

core/arrayUtils.js, core/i18n/resources/en.js, core/objectUtils.js, core/survey/_survey/surveyInfo.js, core/survey/category.js, core/survey/categoryItem.js, core/survey/categoryLevel.js, core/survey/nodeDef.js, core/survey/taxonomy.js, core/validation/_validator/validatorErrorKeys.js, server/modules/category/api/categoryApi.js, server/modules/category/manager/categoryManager.js, server/modules/category/repository/categoryRepository.js, server/modules/category/service/categoryImportJob.js, server/modules/category/service/categoryItemsUpdater.js, server/modules/survey/repository/surveySchemaRepositoryUtils.js, webapp/components/survey/CategoryDetails/CategoryDetails.js
=> Feature - published category import

webapp/components/survey/CategoryDetails/CategoryDetails.scss, webapp/components/survey/CategoryDetails/LevelDetails/ItemDetails/ItemDetails.js
=> fixed: category item warning icon covering code

webapp/components/Map/Map.scss
=> Map: hide Leaflet flag

core/survey/_survey/surveyNodeDefs.js, server/modules/analysis/service/chainSummaryGenerator.js
Result variables entityPath and categoryName
Resolves #2309
=> Chain summary improvements

common/apiRoutes/rChain.js, core/survey/_survey/surveyNodeDefs.js, core/survey/_survey/surveyNodeDefsIndex.js, core/survey/survey.js, server/modules/analysis/api/rChainApi.js, server/modules/analysis/service/index.js, server/modules/analysis/service/rChain/index.js, server/modules/analysis/service/rChain/rChain.js, server/modules/analysis/service/rChain/rFile/system/rFileReadData.js
=> R chain: multiple attributes in separate data frames

webapp/components/survey/NodeDefDetails/store/actions/useGetSiblingNodeDefUuid.js
=> NodeDefDetails: fixed next button brings to blank page

core/survey/_survey/surveyAnalysis.js, core/survey/_survey/surveyNodeDefs.js, server/modules/analysis/service/rChain/index.js, server/modules/surveyRdb/repository/resultNode/massiveUpdateData.js, server/modules/surveyRdb/repository/resultNode/massiveUpdateNodes.js
=> Fixing Rchain persist results

common/analysis/samplingNodeDefs.js, core/survey/_survey/surveyAnalysis.js, core/survey/nodeDef.js, server/modules/analysis/service/chainSummaryGenerator.js, server/modules/analysis/service/rChain/rChain.js, server/modules/analysis/service/rChain/rFile/system/rFilePersistResults.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDef/AnalysisNodeDef.js
resolves #2367 
resolves #2365
=> Chain RStudio: if no active result attribute, omit plot_area_ and entity script from persist-results.R

server/modules/surveyRdb/manager/surveyRdbManager.js
=> Fixed: CSV data export not including _ha variables

server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/service/surveyRdbService.js
=> tentative to fix error fetching viev data counts

webapp/components/Map/mapOptions.js
=> Map: hide option to show/hide control points for non sample based image interpretation surveys

server/modules/analysis/service/chainSummaryGenerator.js
=> Chain summary: added base unit entity keys

server/modules/analysis/service/rChain/rChain.js, server/modules/analysis/service/rChain/rFile/rFile.js, server/modules/analysis/service/rChain/rFile/system/rFileStatisticalAnalysis.js, server/modules/analysis/service/rChain/rFunctions/index.js, server/modules/analysis/service/rChain/rFunctions/utility.js
=> Chain : call statistical analysis after persist results

core/i18n/i18nFactory.js, core/record/nodeKeys.js, core/record/recordValidationReportItem.js, core/validation/validationUtils.js, server/modules/record/api/recordApi.js, server/modules/record/manager/_recordManager/validationReportManager.js, server/modules/record/manager/recordManager.js, server/modules/record/repository/validationReportRepository.js, server/modules/record/service/recordService.js, webapp/components/validationFieldMessages.js, webapp/utils/validationUtils.js, webapp/views/App/views/Data/ValidationReport/Row/Row.js, webapp/views/App/views/Data/ValidationReport/ValidationReport.js, webapp/views/App/views/Data/ValidationReport/ValidationReport.scss, webapp/views/App/views/Home/Dashboard/ActivityLog/store/parsers/i18nMessageParamsFns/node.js
=> Feature / validation report export

webapp/views/App/views/Analysis/Chain/statisticalAnalysis/ChainStatisticalAnalysisProps.js, webapp/views/App/views/Analysis/Chain/statisticalAnalysis/DimensionsSelector/DimensionsSelector.js
=> Chain statistical analysis: clear selected dimensions on entity change

server/modules/analysis/api/chainApi.js
=> changed chain summary json file name

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTable.scss, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableRow.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableRows.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePolygon.js
=> Multiple entity (tables): show vertical scrollbar

webapp/components/Map/MapContext.js, webapp/components/Map/mapOptions.js
=> Map options: fixed default options initialization

server/modules/record/service/recordService.js
=> Validation report: record cycle starts from 1

core/i18n/resources/en.js, server/modules/record/api/recordApi.js, server/modules/record/repository/validationReportRepository.js, server/modules/record/service/recordService.js
=> Validation report access

webapp/views/App/views/Data/Charts/components/DataSelector/DataSelector.scss, webapp/views/App/views/Data/Charts/state/blocks/MetricBlock/index.js
=> fixed error rendering bar chart

core/record/_record/recordReader.js, core/record/node.js, core/record/record.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTreeNode/EntitySelectorTreeNode.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTreeNode/EntitySelectorTreeNode.scss, webapp/components/survey/SurveyForm/nodeDefs/nodeDefSwitch.js, webapp/store/ui/record/reducer.js, webapp/store/ui/record/state.js
=> Hide not applicable pages

webapp/components/DataQuery/ButtonBar/ButtonBar.js, webapp/components/DataQuery/DataQuery.js, webapp/components/DataQuery/QueryNodeDefsSelector/QueryNodeDefsSelector.js, webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js, webapp/components/DataQuery/Visualizer/Table/Row/RowHeader.js, webapp/components/DataQuery/Visualizer/Table/Table.js, webapp/components/DataQuery/Visualizer/Visualizer.js, webapp/components/DataQuery/dataQuery.scss, webapp/components/form/Dropdown/Dropdown.js, webapp/components/form/LabelWithTooltip/LabelWithTooltip.js, webapp/components/survey/NodeDefLabelSwitch/NodeDefLabelSwitch.js, webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesSelector.js, webapp/components/survey/NodeDefsSelector/NodeDefsSelectorAggregate.js
=> Explorer: node def label type selector

core/survey/nodeDefLayoutUpdater.js, server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/nodeDefsImportJob.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityFormGrid.js
=> Bugfix / collect import coordinate attribute layout

webapp/components/survey/NodeDefDetails/store/actions/useGetSiblingNodeDefUuid.js
=> Survey form designer: exclude analysis variables when pressing next/prev buttons

webapp/components/form/Dropdown/Dropdown.js, webapp/components/form/Dropdown/dropdown.scss
=> fixed dropdown not showing properly inside tables

core/survey/_survey/surveyInfo.js, core/survey/survey.js, server/modules/survey/repository/surveyRepository.js, webapp/components/hooks/index.js, webapp/components/hooks/useBrowserLanguageCode.js, webapp/components/survey/Surveys/Surveys.js
=> Surveys list: show labels in browser language or in survey default language

webapp/store/user/hooks.js, webapp/store/user/index.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributeMarker.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.scss, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/convertDataToPoints.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/useCoordinateAttributeDataLayer.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/useOnEditedRecordDataFetched.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataItemPopup.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataLayer.js, webapp/views/App/views/Data/MapView/common/MarkerTooltip.js, webapp/views/App/views/Data/MapView/common/useElevation.js
=> Map / sampling point data layer: added tooltip with codes

core/survey/nodeDef.js, package.json, webapp/components/survey/SurveyForm/nodeDefs/nodeDefs.scss, yarn.lock
=> Bugfix: coordinate attribute can have default value

.env.template, core/processUtils.js, core/user/_user/userPrefs.js, server/modules/user/manager/userManager.js, server/modules/user/repository/userRepository.js, server/modules/user/service/systemAdminUserValidator.js, server/modules/user/service/userService.js, server/server.js, server/system/appCluster.js
=> Feature: insert system admin user on startup

core/expressionParser/expression.js, core/expressionParser/expressionConstants.js, core/expressionParser/helpers/utils.js, server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/collectExpressionConverter.js, server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/validationRuleParser.js, webapp/components/expression/expressionVariables.js, webapp/components/expression/nodes/expressionNode.js, webapp/components/expression/nodes/identifier.js, webapp/components/expression/nodes/literal.js
=> Bugfix / expression editor dates

core/i18n/resources/en.js, webapp/views/App/views/Data/ValidationReport/Row/Row.js
=> Fixed: validation report use preferred survey language

server/modules/analysis/service/rChain/rFile/fileChainSummaryJson.js, server/utils/file/fileUtils.js
=> fixing chain RStudio startup

package.json, webapp/components/DataQuery/QueryNodeDefsSelector/QueryNodeDefsSelector.js, webapp/components/survey/NodeDefsSelector/NodeDefsSelectorAggregate.js, yarn.lock
=> Fixed Explorer in aggregate mode not showing analysis attributes

core/i18n/i18nFactory.js, core/i18n/resources/en.js, server/modules/user/service/userInviteService.js, server/modules/user/service/userService.js, server/utils/mailer.js
=> Fixed text in invite email

.vscode/settings.json, webapp/components/survey/LabelsEditor/LabelsEditor.js, webapp/components/survey/LabelsEditor/LabelsEditor.scss
=> Fixed labels editor: badge overlapping with text

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefCoordinate.scss
=> Coordinate attribute UI: occupy all available space

test/e2e/tests/recordDelete.js, webapp/components/survey/SurveyForm/components/formEntryActions.js, webapp/utils/testId/index.js, webapp/views/App/views/Data/Records/Row/Row.js
=> Record delete: do not allow from record edit view

webapp/components/form/EmailInput.js, webapp/components/form/Input/Input.js, webapp/components/form/index.js, webapp/views/Guest/views/ForgotPassword/ForgotPassword.js, webapp/views/Guest/views/Login/Login.js, webapp/views/Guest/views/Login/Login.scss
=> Fix login email input field: trim text

webapp/views/App/views/Data/Records/HeaderLeft/HeaderLeft.scss
=> fixed records list search input field width

server/modules/auth/authApiMiddleware.js, server/modules/geo/api/geoApi.js, webapp/components/Map/MapBaseLayerPeriodSelector.js, webapp/components/Map/WmtsComponent.js, webapp/components/Map/baseLayers.js, webapp/service/api/index.js, webapp/service/api/map/index.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataItemPopup.js, webapp/views/App/views/Data/MapView/common/useElevation.js, webapp/views/App/views/Home/SurveyInfo/SrsEditor/SrsEditor.js
=> fixed error 500 using Map with analysis user

core/numberUtils.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.scss
=> Map: enhanced marker popup layout

webapp/views/App/views/Home/SurveyInfo/CyclesEditor/CyclesEditor.js
=> Fixed cycle delete message

common/model/csvExport/CsvDataExportModel.js, common/model/db/tables/dataNodeDef/columnNodeDef.js, common/surveyRdb/nodeDefTable.js, core/i18n/resources/en.js, core/survey/nodeDef.js, server/modules/analysis/service/rChain/rFile/system/rFileReadData.js, server/modules/dataImport/service/DataImportJob.js, server/modules/dataImport/service/dataImportFileReader.js, server/modules/dataImport/service/dataImportTemplateService.js, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/repository/dataView/read.js, server/modules/surveyRdb/schemaRdb/dataColProps.js, webapp/components/Accordion/Accordion.js, webapp/components/Accordion/index.js, webapp/components/Dropzone/Dropzone.js, webapp/components/Stepper/Stepper.js, webapp/components/Stepper/index.js, webapp/components/index.js, webapp/components/survey/NodeDefLabelSwitch/NodeDefLabelSwitch.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTree.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTreeNode/EntitySelectorTreeNode.js, webapp/utils/fileUtils.js, webapp/views/App/views/Data/DataImport/DataImport.scss, webapp/views/App/views/Data/DataImport/DataImportCollectView.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.scss, webapp/views/App/views/Data/DataImport/useDataImportCsvViewSteps.js, webapp/views/App/views/Data/ExportData/ExportData.js, webapp/views/App/views/Data/ExportData/ExportData.scss
restored CSV data import improvements + fix in RStudio read-data script
=> CSV data import improvements

webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.scss
=> Fixed: vertical scrollbar hidden in survey hiearchy tree

server/modules/record/repository/recordRepository.js, webapp/views/App/views/Data/Records/RowHeader/RowHeader.js
=> Records list: added sort to "Date last modified" column

core/dateUtils.js, core/i18n/resources/en.js, server/modules/dataImport/service/dataImportFileReader.js
=> CSV data import date format

webapp/components/form/Dropdown/Dropdown.js
=> fixed dropdown items filtering

webapp/views/App/views/Data/Records/HeaderLeft/HeaderLeft.js
=> Fix records list export: only selected cycle

core/i18n/resources/en.js, server/utils/file/csvReader.js
=> CSV data import: skip empty columns

webapp/components/survey/SurveyForm/nodeDefs/nodeDefs.scss, webapp/style/_vars.scss, webapp/style/formBase.scss, webapp/style/main.scss
=> Improved font readability

webapp/components/form/Dropdown/useDropdown.js
=> Fixed paginator/items per page selection

common/analysis/areaBasedEstimatedNodeDef.js, common/analysis/samplingNodeDefs.js, server/modules/analysis/manager/chainsCleanManager.js, server/modules/nodeDef/manager/nodeDefManager.js
=> Fix / area based node def update

webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributeDataLayer.js
=> map: fixed runtime error

webapp/components/Map/baseLayers.js
=> fixed map base layers max zoom level

server/modules/category/service/categoryService.js, server/modules/record/service/recordService.js, server/modules/survey/api/surveyApi.js, server/modules/survey/service/export/jobs/CSVDataExtractionJob.js, server/modules/survey/service/surveyService.js, server/modules/surveyRdb/api/surveyRdbApi.js, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/service/surveyRdbService.js, server/modules/taxonomy/api/taxonomyApi.js, server/utils/exportFileNameGenerator.js, webapp/components/DataGrid/DataGrid.js, webapp/components/DataQuery/ButtonBar/ButtonDownload/ButtonDownload.js, webapp/components/buttons/ButtonMenu.js, webapp/service/api/data/index.js, webapp/store/app/job/actions.js, webapp/store/app/job/hooks.js, webapp/store/app/job/reducer.js, webapp/store/app/job/state.js, webapp/store/ui/exportCsvData/actions.js, webapp/store/ui/surveyForm/state.js, webapp/views/App/JobMonitor/JobErrors/JobErrors.js, webapp/views/App/JobMonitor/JobMonitor.js, webapp/views/App/views/Data/DataImport/DataImportCompleteDialog.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js, webapp/views/App/views/Data/ExportData/ExportData.js
=> Fix / exported CSV file names

core/i18n/resources/en.js, server/modules/category/api/categoryApi.js, server/modules/category/manager/categoryImportTemplateGenerator.js, server/modules/category/service/categoryService.js, webapp/components/survey/CategoryDetails/CategoryDetails.js, webapp/utils/testId/index.js
=> Category import: fixed template for sampling point data import

core/i18n/resources/en.js, webapp/components/survey/ActiveSurveyNotSelected/ActiveSurveyNotSelected.js, webapp/components/survey/ActiveSurveyNotSelected/ActiveSurveyNotSelected.scss, webapp/components/survey/ActiveSurveyNotSelected/index.js, webapp/components/survey/SurveyDefsLoader/SurveyDefsLoader.js
=> Show message when active survey is not selected

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTime.js, webapp/components/survey/SurveyForm/nodeDefs/nodeDefs.scss
=> fixed layout of read-only attributes

core/record/_record/recordReader.js, core/record/nodeValueFormatter.js, core/record/record.js, server/modules/record/api/recordApi.js, server/modules/record/service/recordService.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefFile.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefFile.scss
=> File attribute: added ancestor keys to downloaded file name

core/survey/_survey/surveyInfo.js, core/survey/survey.js, server/modules/arenaImport/service/arenaImport/jobs/usersImportJob.js, webapp/components/modal.scss
=> fixed error importing survey using non-admin user

common/analysis/chain.js, server/modules/analysis/service/rChain/rFile/rFile.js, server/modules/analysis/service/rChain/rFile/system/init-handle-errors.R, server/modules/analysis/service/rChain/rFile/system/rFilePersistResults.js, server/modules/analysis/service/rChain/rFile/system/rFilePersistScriptsGeneric.js, server/modules/analysis/service/rChain/rFile/user/rFileCommonEnd.js
- persist/read common-end script
- added function clearGlobalErrors to clear global errors
=> fixed to chain scripts

server/modules/analysis/service/rChain/rFile/system/init-api.R, server/modules/analysis/service/rChain/rFile/system/init-packages.R, server/modules/analysis/service/rChain/rFile/system/rFileLogin.js
=> Chain / login script: allow uppercase in email

webapp/components/form/checkbox.js, webapp/views/App/views/Home/CollectImportReport/CollectImportReport.js, webapp/views/App/views/Home/CollectImportReport/CollectImportReport.scss, webapp/views/App/views/Home/CollectImportReport/HeaderLeft/HeaderLeft.js, webapp/views/App/views/Home/CollectImportReport/Row/Row.js
=> Collect import report: layout adjustments

webapp/components/survey/NodeDefsSelector/NodeDefsSelector.js, webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js, webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.scss
=> Survey hierarchy: show single entities in entity selector

webapp/components/Table/Header/Paginator/Paginator.js, webapp/style/table.scss
=> Paginator: fixed disabled buttons style

webapp/views/Guest/views/AccessRequest/AccessRequest.js, webapp/views/Guest/views/AccessRequest/AccessRequest.scss, webapp/views/Guest/views/AccessRequest/AccessRequestField.js
=> Access request: do not allow uppercase letters in email field; layout adjustments;

common/model/db/views/dataNodeDef/view.js, core/survey/nodeDef.js, server/modules/surveyRdb/repository/dataView/create.js
=> Fix reading data from RStudio when multiple code attribute is defined

core/i18n/resources/en.js, package.json, yarn.lock
=> Fixed categoryItemProp function not working when used in hierarchical code attributes

core/survey/SamplingPolygon.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributeMarker.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js
=> Map / Open in Earth Map: if survey is not "sample based image interepreted" show default 100x100 square in Earth Map

core/i18n/resources/en.js, core/survey/nodeDef.js, webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js, webapp/components/survey/NodeDefDetails/CoordinateProps.js
=> Coordinate node def: added "Allow only device coordinate" prop

core/i18n/resources/en.js, server/modules/analysis/service/rChain/rFile/system/init-packages.R
=> Fix / RStudio scripts

server/modules/analysis/service/chainSummaryGenerator.js
=> Chain: add stratification and post-stratification attribute category level to chain summary in JSON

server/modules/user/repository/userRepository.js, server/modules/user/service/userExportService.js
=> Users export: add country column

server/modules/analysis/service/chainSummaryGenerator.js
=> Chain summary: added category attribute ancestors

core/i18n/resources/en.js, core/survey/_surveyValidator/surveyInfoValidator.js, core/validation/_validator/validatorErrorKeys.js, core/validation/_validator/validatorFunctions.js, core/validation/validator.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxon.js, webapp/service/api/index.js, webapp/service/api/user/index.js, webapp/store/user/hooks.js, webapp/views/App/views/Users/UserEdit/store/actions/useGetUser.js
fixed some bugs emerged using latest React version (improper use of useEffect returning functions when not necessary)
=> Bug fixing

server/modules/category/service/categoryItemsSummaryBuilder.js
=> Chain / RStudio categories: added code joint column

core/i18n/resources/en.js, core/survey/nodeDefLayout.js, server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob/nodeDefsImportJob.js, webapp/components/survey/NodeDefDetails/AdvancedProps.js, webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js, webapp/components/survey/NodeDefDetails/CoordinateProps.js, webapp/components/survey/NodeDefDetails/NodeDefDetails.scss
=> Node def prop "hiddenInMobile"

webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnDataEdit.js, webapp/components/DataQuery/Visualizer/Table/Table.js, webapp/components/DataQuery/Visualizer/Table/store/hooks/useListenToNodeUpdates.js, webapp/components/DataQuery/Visualizer/Visualizer.js, webapp/components/DataQuery/store/useDataQuery.js, webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefTableCellBody.js, webapp/store/ui/record/hooks/index.js, webapp/store/ui/record/index.js
=> Fix / data explorer issues

server/modules/category/api/categoryApi.js, server/modules/category/manager/categoryImportSummaryGenerator.js, server/modules/category/manager/categoryManager.js, server/modules/collectImport/service/collectImport/metaImportJobs/samplingPointDataImportJob.js
=> category import: allow importing labels and description with default lang code

webapp/views/App/Header/UserPopupMenu/UserPopupMenu.js
=> moved change password link before logout

package.json, test/unit/tests/002recordExpressionParser.test.js, yarn.lock
=> use latest arena-core version

common/model/db/tables/dataNodeDef/columnNodeDef.js, core/survey/_survey/surveyNodeDefs.js, server/modules/surveyRdb/schemaRdb/dataColProps.js, webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js, webapp/components/survey/NodeDefDetails/BasicProps/store/useIsMultipleEditDisabled.js, webapp/components/survey/NodeDefDetails/TaxonProps.js
=> Survey templates: allow editing props

core/survey/nodeDefLayout.js
=> fixed layout of form with hidden attributes

server/modules/survey/service/export/exportCsvDataJob.js, server/utils/file/fileUtils.js
=> Fix data export with option "incldue data from all cycles" not including all entities

webapp/components/survey/NodeDefDetails/ButtonBar.js
=> Node def editor: hide next/prev buttons when creating new node defs

server/modules/record/service/fileService.js, server/server.js, webapp/components/survey/SurveyForm/nodeDefs/nodeDefs.scss
- run files migrations after DB migraions
- run surveys files migrations sequentially, not in parallel
=> Files migration

server/modules/mobile/api/mobileApi.js
advanced props are necessary for read-only attributes, default values etc.
=> include advanced props in mobile api survey fetch

server/modules/record/service/recordService.js, webapp/store/ui/record/actions/delete.js
=> fixed multiple attribute delete

webapp/components/Table/useTable.js
=> fixed survey list filter

test/e2e/tests/_surveyCreate/index.js, test/e2e/tests/_templateCreate/index.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTreeNode/EntitySelectorTreeNode.js, webapp/components/survey/SurveyForm/nodeDefs/components/NodeDefFormItem/NodeDefFormItemLabel.js, webapp/components/survey/SurveyForm/nodeDefs/components/NodeDefIconKey/NodeDefIconKey.js, webapp/components/survey/SurveyForm/nodeDefs/nodeDefs.scss, webapp/views/App/Header/Header.js
=> Page navigation bar: hide non-accessible pages

server/modules/taxonomy/manager/taxonomyManager.js, server/modules/taxonomy/repository/taxonomyRepository.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxonAutocompleteDialog.js
=> fixed taxon vernacular name search

core/survey/categoryExportFile.js, server/modules/category/manager/categoryImportSummaryGenerator.js, server/modules/category/manager/categoryImportTemplateGenerator.js, server/modules/category/repository/categoryExportRepository.js
=> Flat category import/export: use "code" as column header

core/survey/_survey/surveyInfo.js
=> Survey SRS index: always include default srs

package.json, server/modules/record/service/fileService.js, yarn.lock
=> Fixed CSV data import in survey with hierarchical code attributes as key

core/i18n/resources/en.js, webapp/views/App/views/Analysis/Chain/ButtonBar/ButtonBar.js
=> Chain: changed delete button label

server/modules/category/repository/categoryRepository.js, server/modules/expression/api/expressionApi.js
=> fixed error setting default value in hierarchical code attribute

server/modules/category/service/CategoriesExportJob.js, server/modules/survey/service/export/jobs/CategoriesExportJob.js
=> fixed categories export

server/modules/category/api/categoryApi.js, webapp/service/api/categories/index.js, webapp/service/api/index.js, webapp/views/App/views/Data/Records/Records.js, webapp/views/App/views/Data/Records/Row/Row.js, webapp/views/App/views/Data/Records/RowHeader/RowHeader.js, webapp/views/App/views/Data/Records/useNodeDefKeysCategoryItemsInLevel.js
=> Enhancement / records list: show category item labels

webapp/components/survey/Surveys/Surveys.js
=> surveys list: show tooltip on mouse over when name or label are too long

core/survey/nodeDefLayoutSizes.js, core/survey/nodeDefLayoutUpdater.js, server/modules/nodeDef/manager/nodeDefManager.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityFormGrid.js, webapp/components/survey/SurveyForm/nodeDefs/nodeDefUIProps.js
=> Survey form: handle min/max height of grid items

server/modules/arenaImport/service/arenaImport/jobs/createRdb.js, webapp/views/App/views/Data/Records/Records.js, webapp/views/App/views/Data/Records/useNodeDefKeysCategoryItemsInLevel.js
=> Fix: error 500 in records list when survey is from Collect

core/i18n/resources/en.js, core/survey/nodeDef.js, server/modules/nodeDef/manager/nodeDefAreaBasedEstimateManager.js, server/modules/nodeDef/manager/nodeDefManager.js, server/modules/nodeDef/repository/nodeDefRepository.js, server/modules/survey/service/publish/jobs/nodeDefsValidationJob.js, webapp/components/survey/NodeDefDetails/AnalysisProps/AreaBasedEstimated/AreaBasedEstimated.js
=> Fixed area based estimate node def creation (avoid creating empty _ha node defs)

package.json, server/modules/record/manager/_recordManager/recordUpdateManager.js, yarn.lock
=> fixed validation of attributes inside multiple entities

server/modules/survey/service/schemaSummary/schemaSummary.js, test/e2e/tests/surveySchemaSummary.js, webapp/components/survey/SurveyCreate/SurveyCreate.js
=> Schema summary: added new fields

core/i18n/resources/en.js, core/survey/_survey/surveyDependencyTypes.js, core/survey/_surveyValidator/nodeDefExpressionsValidator.js, core/survey/_surveyValidator/nodeDefValidator.js, core/survey/nodeDef.js, package.json, webapp/components/ScriptEditor/ScriptEditor.js, webapp/components/survey/NodeDefDetails/AdvancedProps.js, webapp/components/survey/NodeDefDetails/CodeProps.js, webapp/components/survey/NodeDefDetails/TaxonProps.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCode.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/store/hooks/useItems.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxon.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxonAutocompleteDialog.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxonInputField.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/useItemsFilter.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/useTaxa.js, yarn.lock
=> Items filter

server/modules/analysis/service/chainSummaryGenerator.js
=> chain summary: added decimalDigits

core/i18n/resources/en.js, webapp/components/buttons/ButtonIconInfo.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/useItemsFilter.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.scss
=> data import CSV: added info icon button

package.json, webapp/components/survey/NodeDefDetails/store/useNodeDefDetails.js, webapp/store/survey/status/state.js, yarn.lock
=> chain: do not mark survey as draft when opening a node def for edit

core/i18n/resources/en.js, core/objectUtils.js, core/survey/nodeDef.js, core/uniqueNameGenerator.js, server/modules/survey/service/surveyUniqueNameGenerator.js, webapp/components/survey/SurveyForm/nodeDefs/components/entitySelectorDialog.js, webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefEditButtons.js, webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefEditButtons.scss, webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefEditButtonsMenu.js, webapp/store/survey/nodeDefs/actions.js
=> Feature: attribute clone

webapp/components/survey/NodeDefDetails/store/useNodeDefDetails.js, webapp/store/survey/hooks/index.js
=> fixed form designer arrows stopped working

server/modules/surveyRdb/manager/surveyRdbManager.js
=> data export: do not include record cycle if survey has only 1 cycle

server/modules/category/api/categoryApi.js
=> fixed error fetching records

webapp/components/survey/CategoryList/store/actions/useDelete.js, webapp/store/survey/categories/state.js, webapp/store/survey/taxonomies/state.js
=> fixed validation error using categoryItemProp function with new category

core/survey/nodeDefLayout.js, core/survey/survey.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntitySwitch.js
=> fixed layout of forms with attributes becoming relevant

core/survey/_survey/surveyInfo.js, core/survey/survey.js, server/modules/survey/manager/surveyManager.js, server/modules/surveyRdb/repository/schemaRdbRepository.js, webapp/components/survey/SurveyDefsLoader/SurveyDefsLoader.js
=> fixed error shown accessing Records or Validation Report for unpublished survey from Collect

webapp/components/expression/expressionEditor.js
=> Advanced expression editor: show attribute name instead of label

webapp/components/Map/Map.js, webapp/components/Map/MapMarker/MapMarker.js, webapp/components/Map/MapMarker/useMapMarker.js, webapp/components/Map/useMap.js
=> Map: layout adjustments

core/i18n/resources/en.js, webapp/components/ScriptEditor/ScriptEditor.js, webapp/components/survey/NodeDefDetails/AnalysisProps/RScriptEditor/RScriptEditor.js, webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDefsHeader/AnalysisNodeDefsHeader.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDefsHeader/AnalysisNodeDefsHeader.scss
=> Chain - variable properties: enhances to UI

webapp/views/App/SideBar/SideBar.js, webapp/views/App/SideBar/SideBar.scss
=> sidebar layout adjustments

core/auth/authorizer.js, core/i18n/resources/en.js, core/user/_user/userProps.js, core/user/user.js, server/modules/user/manager/userManager.js, webapp/views/App/views/Users/UserEdit/UserEdit.js, webapp/views/App/views/Users/UserEdit/store/useEditUser.js
=> Maximum number of surveys user can create: make it editable to system admins

core/i18n/resources/en.js, webapp/style/main.scss, webapp/views/Arena/Arena.js
=> System error page: make it less scary

webapp/views/Guest/views/AccessRequest/SurveyTemplateSelect.js
=> fixed user access request template dropdown: show language label instead of code

webapp/components/PanelRight/PanelRight.js, webapp/components/PanelRight/panelRight.scss, webapp/components/survey/CategoryDetails/CategoryDetails.js, webapp/components/survey/CategoryDetails/CategoryDetails.scss, webapp/components/survey/CategorySelector/CategorySelector.js, webapp/style/_vars.scss, webapp/views/App/AppView.js, webapp/views/App/AppView.scss, webapp/views/App/SideBar/SideBar.scss
=> Category details layout

server/modules/record/repository/recordRepository.js
=> records list: allow searching by category item label too

core/i18n/resources/en.js, core/survey/_survey/surveyNodeDefs.js, core/survey/survey.js, server/modules/category/service/CategoriesExportJob.js, server/modules/dataImport/service/dataImportTemplateService.js, server/modules/record/api/recordApi.js, server/utils/file/zipArchiver.js, webapp/components/buttons/ButtonIconInfo.js, webapp/service/api/data/index.js, webapp/service/api/index.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.scss
=> Data import from CSV: change exported file name; allow downloading all templates

webapp/views/App/views/Home/Dashboard/Dashboard.js
=> Hide everything for non-admins

webapp/components/expression/expressionEditorPopup.scss
=> fixed expression editor layout in small displays

core/arrayUtils.js, core/i18n/resources/en.js, core/survey/_survey/surveyCategories.js, core/survey/nodeDef.js, webapp/views/Arena/Arena.js
=> Fixed unused categories warning

webapp/components/DataQuery/valueFormatter.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/convertDataToPoints.js
=> Map: show category item keys in coordinate attribute popup

server/modules/record/manager/recordManager.js, server/modules/record/repository/recordRepository.js, server/modules/user/service/userService.js, webapp/views/App/views/Users/UsersList/UsersList.js
=> Assign records owner to survey admin when user is removed from survey

core/record/_record/recordUpdater.js, server/modules/dataImport/service/DataImportJob/DataImportJob.js, server/modules/record/service/update/thread/recordsUpdateThread.js, webapp/components/expression/expressionEditorPopup.scss, webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCode.js
=> Node delete: code cleanup; remove records from RecordsUpdateThread cache on data import complete;

core/survey/_survey/surveyNodeDefs.js, core/survey/survey.js, server/modules/dataImport/service/dataImportTemplateService.js
=> Data import / download all templates: include nested multiple entities

common/analysis/areaBasedEstimatedNodeDef.js, server/modules/nodeDef/manager/nodeDefManager.js
=> Area-based estimate variable: set label using source attribute label

core/arrayUtils.js, core/i18n/resources/en.js, server/modules/analysis/service/chainSummaryGenerator.js, webapp/views/App/views/Analysis/Chain/Chain.scss
=> Chain / category attributes: sort them by category and level index

server/job/job.js, server/modules/arenaImport/service/arenaImport/jobs/filesImportJob.js, server/modules/mobile/service/arenaMobileDataImport/jobs/recordsImportJob.js, webapp/views/App/views/Analysis/Chain/ChainRStudioFieldset.js
=> data import: throw error when file content is missing; ignore invalid nodes (maybe deleted); chain: hide Include entities without data option

common/model/db/tables/dataNodeDef/columnNodeDef.js, server/modules/surveyRdb/repository/dataView/create.js, webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js, webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.scss
=> Explorer: show labels for multiple attributes

core/survey/nodeDef.js, webapp/components/survey/NodeDefDetails/store/actions/useSetProp.js
=> node def edit: set label according to name when updating it

common/analysis/samplingNodeDefs.js, server/modules/survey/service/schemaSummary/schemaSummary.js, test/e2e/tests/surveySchemaSummary.js
=> Enhancements to schema summary

webapp/components/expression/nodes/binaryOperand.js
=> Expression builder: hide Const button when not necessary

common/apiRoutes/index.js, common/apiRoutes/survey.js, server/modules/analysis/service/rChain/rFile/system/rFileReadData.js, server/modules/survey/service/schemaSummary/schemaSummary.js
=> R chain: include schema summary

webapp/views/App/views/Data/Records/HeaderLeft/HeaderLeft.js
=> Records list: hide Clone button when there are no records

server/modules/surveyRdb/repository/dataView/read.js, webapp/store/user/hooks.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/convertDataToPoints.js
=> Map coordinate attribute popup: show record owner name

server/modules/surveyRdb/repository/dataTableInsertRepository.js, server/modules/surveyRdb/schemaRdb/dataTable.js
=> Survey publish: keep analysis attributes' values

webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.scss, webapp/views/App/views/Designer/SurveyHierarchy/Tree/Tree.js
=> Survey hierarchy: layout adjustments

server/modules/surveyRdb/manager/surveyRdbCsvExport.js
=> fixed error exporting data expanding code attribute columns

webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js
=> fixed Explorer table headers

core/survey/categoryItem.js, webapp/components/survey/CategoryDetails/LevelDetails/ItemDetails/ItemDetails.js
=> category item code: allow some special characters

server/modules/survey/service/schemaSummary/schemaSummary.js, test/e2e/tests/surveySchemaSummary.js
=> add items filter to schema summary

webapp/components/survey/NodeDefDetails/store/actions/useSetProp.js, webapp/components/survey/NodeDefDetails/store/actions/useValidate.js, webapp/components/survey/NodeDefDetails/store/state/state.js
=> node def editor: fixed cannot insert letters with accent in labels and descriptions

core/survey/taxonomy.js, server/modules/taxonomy/manager/taxonomyImportManager.js, server/modules/taxonomy/service/taxonomyImportJob.js, webapp/components/survey/TaxonomyDetails/TaxaTableRow/TaxaTableRow.js, webapp/components/survey/TaxonomyDetails/TaxaTableRowHeader/TaxaTableRowHeader.js, webapp/components/survey/TaxonomyDetails/TaxonomyDetails.js
=> fixed taxonomy import extra props order

webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCodeDropdown/NodeDefCodeDropdown.js, webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxonAutocompleteDialog.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.scss
=> CSV data import: clear file selection on job complete

server/modules/dataImport/service/DataImportJob/dataImportFileReader.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.js
=> CSV data import: do not clear file selection after file validation

core/validation/validation.js, server/modules/record/manager/_recordManager/recordValidationManager.js, web-resources/index.html
fixes #3275 
honestly I don't know/remember why the validation.merge funciton is done in that way, I would just replace the "fields" validations with the new ones, but there could be cases where the validation is done partially and you need to merge the existing one with the new one.
=> Fixing validation of multiple root key attributes 

core/i18n/resources/en.js, core/survey/nodeDef.js, core/survey/nodeDefLayout.js, core/survey/nodeDefLayoutUpdater.js, web-resources/index.html, webapp/components/survey/NodeDefDetails/AdvancedProps.js, webapp/components/survey/NodeDefDetails/NodeDefDetails.scss, webapp/components/survey/NodeDefDetails/store/actions/useSetProp.js
=> Survey designer: added "Include in multiple entity summary" option

core/survey/nodeDef.js, webapp/components/survey/NodeDefDetails/AdvancedProps.js
=> hide mobile props when not available

webapp/views/App/views/Home/Dashboard/SurveyInfo/SurveyInfo.scss
=> Home screen: show full survey name if there is space for it

webapp/components/hooks/useFormObject.js, webapp/components/survey/CycleSelector/CycleSelector.js, webapp/views/App/views/Home/SurveyInfo/CyclesEditor/CyclesEditor.js, webapp/views/App/views/Home/SurveyInfo/SurveyInfo.js, webapp/views/App/views/Home/SurveyInfo/store/useSurveyInfoForm.js
=> cycle delete: reset default cycle key

webapp/components/expression/expressionVariables.js
=> basic expression editor: hide analysis variables

webapp/components/survey/SurveyForm/components/formEditActions.js, webapp/store/ui/record/actions/create.js, webapp/store/ui/surveyForm/reducer.js, webapp/store/ui/surveyForm/state.js, webapp/views/App/views/Data/Records/HeaderLeft/HeaderLeft.js
=> preview: start at root entity level

core/expressionParser/helpers/operators.js, webapp/components/expression/nodes/binary.js, webapp/components/expression/nodes/useAvailableOperatorValues.js, webapp/store/survey/hooks/index.js, webapp/store/survey/index.js
=> Expression editor: filter available operators

core/i18n/resources/en.js, core/survey/_survey/surveyDependencies.js, webapp/components/expression/expressionEditorPopup.js, webapp/components/expression/expressionEditorPopup.scss, webapp/components/expression/expressionEditorPopupState.js, webapp/components/expression/expressionVariables.js, webapp/components/expression/nodes/binaryOperand.js, webapp/components/expression/nodes/literal.js, webapp/components/survey/NodeDefDetails/AdvancedProps.js, webapp/components/survey/NodeDefDetails/ExpressionsProp/NodeDefExpressionsProp.js, webapp/components/survey/NodeDefDetails/store/actions/useValidate.js, webapp/store/survey/nodeDefs/actions.js
=> Expression editor: hide this var

common/model/query/query/query.js, server/modules/survey/service/export/jobs/FilesExportJob.js, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/service/surveyRdbService.js
=> CSV data export: export only files related to exported records

server/modules/survey/service/schemaSummary/schemaSummary.js, test/e2e/tests/surveySchemaSummary.js
=> Schema summary parent code

server/modules/analysis/service/rChain/index.js, server/modules/analysis/service/rChain/rChain.js, server/modules/analysis/service/rChain/rFile/rFile.js, server/modules/analysis/service/rChain/rFunctions/utility.js, server/modules/dataImport/service/DataImportJob/DataImportJob.js, server/modules/nodeDef/manager/nodeDefManager.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDef/AnalysisNodeDef.js, webapp/views/App/views/Analysis/Chain/AnalysisNodeDefs/AnalysisNodeDef/AnalysisNodeDef.scss
=> Chain RStudio: improvements

core/i18n/resources/en.js, webapp/components/buttons/Button.js, webapp/components/survey/CategoryDetails/CategoryDetails.js, webapp/components/survey/CategoryDetails/CategoryDetails.scss, webapp/components/survey/CategoryDetails/LevelDetails/ItemDetails/ItemDetails.js, webapp/components/survey/CategoryDetails/LevelDetails/ItemsList.js, webapp/components/survey/CategoryDetails/LevelDetails/LevelDetails.js, webapp/components/survey/CategoryDetails/store/actions/item/useUpdateItemProp.js, webapp/service/api/categories/index.js, webapp/service/api/index.js
=> Fix: cannot insert accented characters in category item editor

core/objectUtils.js, core/survey/category.js, core/survey/categoryItem.js, core/survey/categoryLevel.js, core/survey/nodeDef.js, core/survey/taxon.js, core/survey/taxonVernacularName.js, core/survey/taxonomy.js, server/modules/arenaImport/service/arenaImport/arenaImportJob.js, server/modules/arenaImport/service/arenaImport/jobs/surveyCreatorJob.js, server/modules/category/repository/categoryRepository.js, server/modules/nodeDef/repository/nodeDefRepository.js, server/modules/taxonomy/repository/taxonomyRepository.js, webapp/components/survey/SurveyCreate/store/actions/useOnImport.js
=> survey import: always import survey as draft if not importing data

webapp/components/survey/SurveyDefsLoader/SurveyDefsLoader.js, webapp/store/survey/actions/defs.js, webapp/store/survey/actions/index.js, webapp/store/survey/categories/state.js, webapp/store/survey/hooks/index.js, webapp/store/survey/status/reducer.js, webapp/store/survey/status/state.js
=> Survey preview: reload survey ref data

webapp/views/Guest/Guest.scss
tentative to make vertical scrollbar in registration page visible on low resolution screens, even if it should already be like this
=> guest pages: layout adjustments

server/modules/category/service/categoryImportJob.js
=> Fixed collect import not assigning category to node defs

webapp/views/App/views/Data/DataImport/DataImportArenaView.js
=> Arena data import: reset file on import complete

core/survey/_survey/surveyInfo.js, core/survey/survey.js, webapp/views/App/views/Home/Dashboard/Dashboard.js, webapp/views/App/views/Home/Dashboard/RecordsSummaryPeriodSelector/store/useRecordsSummary.js
=> survey dashboard: refresh on survey unpublish

server/modules/surveyRdb/repository/dataTableUpdateRepository.js
=> fixed RDB updates (multiple attributes)

webapp/components/form/Dropdown/Dropdown.js, webapp/components/survey/CategorySelector/CategorySelector.js, webapp/components/tooltip.js, webapp/components/tooltip.scss, webapp/components/validationTooltip.js
fixes #3385 
in a near future, Tooltip (tooltip.js), used only by ValidationTooltip, will be replaced by TooltipNew (that uses MUI Tooltip)
=> Dropdown: show validation tooltip on top

package.json, yarn.lock
=> Fixed validation / relevancy and required rules evalutation

core/survey/categoryItem.js, server/modules/surveyRdb/repository/dataView/read.js, webapp/components/survey/CategoryDetails/LevelDetails/ItemDetails/ItemDetails.js
=> data explorer: show multiple attribute label in table

server/job/job.js, server/modules/dataExport/service/DataExportJob/jobs/ZipCreationJob.js, server/modules/surveyRdb/api/surveyRdbApi.js, server/modules/surveyRdb/service/surveyRdbService.js, server/utils/file/fileUtils.js, server/utils/file/zipUtils.js, webapp/components/DataQuery/ButtonBar/ButtonBar.js, webapp/components/DataQuery/ButtonBar/store/state/state.js, webapp/components/DataQuery/ButtonBar/store/useButtonBar.js, webapp/components/DataQuery/DataQueryExportModal/DataQueryExportModal.js, webapp/components/DataQuery/DataQueryExportModal/DataQueryExportModal.scss, webapp/components/DataQuery/DataQueryExportModal/index.js, webapp/service/api/data/index.js, webapp/views/App/views/Data/DataExport/DataExport.js, webapp/views/App/views/Data/DataExport/DataExport.scss, webapp/views/App/views/Data/DataExport/DataExportOptionsPanel.js, webapp/views/App/views/Data/DataExport/dataExportOptions.js
=> Data explorer / csv export: show options

webapp/style/main.scss, webapp/views/Arena/Routes/Notification/Notification.scss, webapp/views/Guest/Error/Error.scss
fixes "send request" button not visible in access request page
=> access request: layout adjustments (mobile devices)

server/modules/category/repository/categoryRepository.js, webapp/store/survey/hooks/index.js
=> Records list: sort keys

common/model/csvExport/CsvDataExportModel.js, webapp/components/survey/NodeDefsSelector/EntitySelectorTree/EntitySelectorTreeNode/EntitySelectorTreeNode.js
=> Data import: include readonly key attributes in templates

core/auth/authorizer.js, server/modules/auth/authApiMiddleware.js, server/modules/survey/api/surveyApi.js, server/modules/survey/manager/surveyManager.js, server/modules/survey/repository/surveyRepository.js, server/modules/survey/service/surveyService.js, webapp/components/survey/Surveys/HeaderLeft/HeaderLeft.js, webapp/store/user/hooks.js
=> Surveys list export

webapp/views/App/views/Data/MapView/SamplingPointDataLayer/useSamplingPointDataLayer.js
=> map / sampling point data layer: show loader when fetching items

core/auth/authorizer.js
=> user email editing: allow only to system admin

core/numberUtils.js, webapp/components/DataQuery/Visualizer/DataQueryTable/Row/Column/ColumnData.js, webapp/components/DataQuery/valueFormatter.js
=> Data explorer: format area based estimated of decimal attributes using referenced node def prop

server/modules/dataImport/service/DataImportJob/dataImportCsvFileReader.js, server/modules/dataImport/service/DataImportJob/dataImportFileReader.js, server/modules/surveyRdb/repository/RdbUpdates.js
=> CSV data import: allow importing files specifying UUID

core/numberUtils.js, core/survey/_survey/surveyNodeDefs.js, core/survey/categoryItem.js, core/survey/survey.js, webapp/charts/PieChart/PieChart.js, webapp/components/DataQuery/Visualizer/DataQueryChart/DataQueryPieChart.js, webapp/components/DataQuery/Visualizer/DataQueryChart/useDataQueryChartData.js, webapp/components/DataQuery/valueFormatter.js
=> Data explorer pie chart: limit decimal digits in values; show percentage;

webapp/store/login/validator.js, webapp/views/Guest/views/ResetPassword/store/hooks.js
=> Reset password: do not validate name and title

web-resources/index.html
use the property defined under Open Foris Initiative Google account to manage all the platforms, including Arena, in a single place.
=> use OpenForis Google Analytics property

common/model/query/query/query.js
=> Data explorer: clear filter and sort on query mode change

webapp/components/DataQuery/Visualizer/DataQueryTable/Row/Column/CustomAggregateFunctionsEditor/CustomAggregateFunctionsEditor.scss, webapp/components/buttons/ButtonCancel.js, webapp/components/expression/expressionEditorPopup.scss, webapp/components/form/Input/Input.js, webapp/components/form/SimpleTextInput.js, webapp/components/survey/ExtraPropDefsEditor/ExtraPropDefEditor.js, webapp/components/survey/NodeDefDetails/NodeDefDetails.js, webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefEntitySelectorDialog.js, webapp/views/App/views/Data/DataImport/DataImportCsvView.scss, webapp/views/Arena/Routes/DialogConfirm/DialogConfirm.js
also fixed text input cursor moving at the end when text is transformed
=> Layout adjustments; fixed text input cursor moving at the end;

core/systemError.js, server/modules/category/api/categoryApi.js, server/modules/category/manager/categoryManager.js, webapp/components/survey/CategoryDetails/store/actions/category/useUploadCategory.js, webapp/style/_vars.scss, webapp/style/cssVars.scss, webapp/views/Arena/Routes/Notification/Notification.scss
=> Category import: handle errors

core/record/_record/recordKeys.js, core/record/record.js, server/modules/record/service/recordService.js
=> Records list export: added files count and size

core/survey/_surveyValidator/nodeDefValidator.js, core/validation/_validator/validatorFunctions.js, core/validation/validator.js, webapp/components/form/Input/Input.js, webapp/components/survey/NodeDefDetails/DecimalProps.js
=> Decimal attribute: allow 0 as max decimal numbers

core/i18n/resources/en/common.js, server/modules/geo/api/geoApi.js, web-resources/img/of_whisp_icon.svg, webapp/components/buttons/Button.js, webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js
=> Map view: added button to generate data from Whisp

core/auth/authorizer.js, server/modules/auth/authApiMiddleware.js, server/modules/record/api/recordApi.js
=> fixed record owner change error

core/i18n/resources/en/common.js, webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js
=> changed label "Included in data" into " Included in cloned data"

webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js
=> fixed map coordinate numeric fields precision in popup

core/i18n/resources/en/common.js, core/survey/nodeDef.js, webapp/components/expression/expressionEditor.js, webapp/components/survey/NodeDefDetails/AdvancedProps.js, webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js, webapp/components/survey/NodeDefDetails/BasicProps/store/useBasicProps.js, webapp/components/survey/NodeDefDetails/BasicProps/store/useIsKeyEditDisabled.js, webapp/components/survey/NodeDefDetails/ExpressionsProp/ExpressionProp.js, webapp/components/survey/NodeDefDetails/ExpressionsProp/ExpressionsProp.js, webapp/components/survey/NodeDefDetails/ExpressionsProp/NodeDefExpressionsProp.js, webapp/components/survey/NodeDefDetails/store/actions/useSetProp.js
=> Auto incremental key

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefBoolean.scss
=> fixed boolean attribute layout issue

core/i18n/resources/en/common.js, core/record/_record/recordNodesUpdater.js, webapp/components/DataGrid/DataGrid.js, webapp/views/App/JobMonitor/JobErrors/JobErrors.js
=> Fix job errors export to CSV

server/modules/auth/authApiMiddleware.js, webapp/components/survey/SurveyCreate/store/actions/useOnCreate.js
=> survey create: improve error message if max number of surveys is reached

core/i18n/resources/en/common.js, core/survey/_survey/surveyInfo.js, core/survey/survey.js, core/user/_user/userKeys.js, core/user/user.js, server/modules/user/repository/userRepository.js, server/modules/user/service/userService.js, webapp/views/App/views/Users/UsersList/UsersList.js, webapp/views/App/views/Users/UsersList/useUsersListColumns.js
=> Show surveys count in users list

core/i18n/resources/en/common.js, core/survey/extraPropDef.js, core/survey/extraPropDefsUpdater.js, server/modules/category/manager/categoryManager.js, server/modules/taxonomy/manager/taxonomyManager.js, test/e2e/tests/surveyFormPreview.js, webapp/components/expression/nodes/call/call.js, webapp/components/survey/ExtraPropDefsEditor/ExtraPropDefsEditor.js, webapp/components/survey/ExtraPropDefsEditor/ExtraPropDefsEditor.scss, webapp/views/App/views/Home/SurveyInfo/SurveyInfo.js, webapp/views/App/views/Home/SurveyInfo/SurveyUserExtraPropDefsEditor/SurveyUserExtraPropDefsEditor.js
=> fixed survey user extra props editor not working properly

.mergify.yml
fixed warning in GitHub actions
=> updated Mergify configuration

webapp/components/Table/Content/Content.js, webapp/components/Table/Content/ContentHeader.js, webapp/components/Table/Content/ContentHeaders.js, webapp/components/Table/Table.js, webapp/components/Table/TableSelectionColumn.js, webapp/components/Table/useTable.js, webapp/components/form/checkbox.js, webapp/views/App/views/Data/Records/useColumns.js
=> Records list: allow selecting all visible records; hide "created with app" icon;

webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/store/useSortEditor.js
=> Data explorer: keep order of selected dimensions in sort editor

webapp/views/App/views/Data/ValidationReport/Row/Row.js, webapp/views/App/views/Data/ValidationReport/ValidationReport.js, webapp/views/App/views/Data/ValidationReport/ValidationReport.scss
=> Validation report: layout adjustments

package.json, webapp/style/table.scss, webapp/views/App/views/Data/Records/Records.scss, yarn.lock
=> records list: added margin to the right of files column

server/modules/dataExport/service/DataExportJob/DataExportJob.js
=> fixed CSV data import including files and categories

webapp/components/geo/GeoPolygonInfo.js, webapp/utils/geoJsonUtils.js, webapp/views/App/views/Data/MapView/GeoAttributeDataLayer/convertDataToGeoJsonPoints.js, webapp/views/App/views/Data/MapView/SamplingPointDataLayer/useSamplingPointDataLayer.js
=> Geo attribute: support feature collection

webapp/components/Map/MapOptionsEditor.js, webapp/components/Map/useMap.js, webapp/utils/geoJsonUtils.js, webapp/views/App/views/Data/MapView/GeoAttributeDataLayer/convertDataToGeoJsonPoints.js
=> geo attribute / show map: center map to polygon centroid

webapp/components/expression/nodes/binaryOperand.js, webapp/components/expression/nodes/expressionNode.js
=> Fixed unary expression editing

common/analysis/chain.js, core/i18n/resources/en/common.js, core/record/recordSummary.js, server/modules/analysis/service/rChain/index.js, webapp/service/api/data/index.js, webapp/service/api/index.js, webapp/views/App/views/Analysis/Chain/Chain.js, webapp/views/App/views/Analysis/Chain/ChainRStudioFieldset.js, webapp/views/App/views/Analysis/Chain/RecordsDropdown.js
=> Analysis chain: allow exporting to RStudio only selected records

webapp/utils/domUtils.js, webapp/views/App/JobMonitor/JobErrors/JobErrors.js
=> Job dialog / errors export: fixed character encoding issue

server/modules/surveyRdb/manager/surveyRdbManager.js
=> CSV data export (with ancestors): put key and ancestor columns first

webapp/components/survey/NodeDefDetails/ValidationsProps.js
=> Min/max count: open expression editor selecting Variable

server/modules/survey/service/schemaSummary/schemaSummary.js
=> schema summary export: show min/max count expressions

common/model/db/tables/dataNodeDef/dataColProps.js
=> data export: include EPSG: prefix in coordinate SRS column

core/i18n/resources/en/common.js, server/modules/dataImport/service/DataImportJob/dataImportFlatDataFileReader.js
=> data import: added more formats for date and time import

core/record/_record/recordsCombiner.js, test/unit/tests/015recordsMerge.test.js
=> Records merge / multiple attributes: keep values from both records

common/model/csvExport/CsvDataExportModel.js
=> Data import template: fixed coordinate attribute fields order

webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefFile.js
=> File attribute: hide delete button when record is not editable

common/model/db/sql/sqlSelectBuilder.js, core/i18n/resources/en/appErrors.js, server/modules/surveyRdb/manager/surveyRdbManager.js, server/modules/surveyRdb/repository/dataView/index.js, server/modules/surveyRdb/repository/dataView/read.js, server/utils/streamUtils.js
=> Data export: determine if data can be exported to Excel before starting data export process

core/i18n/resources/en/common.js, core/i18n/resources/en/surveyForm.js, core/i18n/resources/mn/surveyForm.js, core/i18n/resources/ru/common.js, core/i18n/resources/ru/surveyForm.js
=> fixed taxonomy table / scientific name header

webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js
=> Form header: hide "included in cloned data" option

webapp/views/App/Header/Header.scss
=> Enlarge language selector

core/survey/categoryImportSummary.js, server/modules/category/manager/categoryImportSummaryGenerator.js, webapp/components/survey/CategoryDetails/ImportSummary/ImportSummary.js
=> fixed category import items count

webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/store/useSortEditor.js
=> data explorer / sort editor: allow sorting by analysis variables

server/threads/thread.js, server/threads/threadManager.js, webapp/views/Arena/Arena.js
=> Handle record update thread errors
