openforis/arena

core/i18n/resources/en.js
webapp/loggedin/modules/designer/surveyInfo/components/cyclesEditor.js

Should be straightforward. I'm mainly just wondering if this could be a systematic issue.
`cycle` (`step`) is stored as a string, but it's really a number, leading to these sorts of issues.
The error message would previously be like `"5" + 1` -> `cycle 51`.

Fix typo in cycle editor message

---

webapp/loggedin/surveyViews/surveyForm/components/addNodeDefPanel.js

NodeDefLayout.isRenderTable is typed like
`isRenderTable: cycle => nodeDef => boolean`
Previously `disabled` was sometimes a function rather than a boolean.

addNodeDefPanel.js: Actually invoke isRenderTable

---

webapp/loggedin/appHeader/components/userPopupMenu.scss
webapp/style/_vars.scss

The user menu should have the highest precedence since it has to be explicitly toggled on.
Currently it gets hidden behind some elements (e.g. the nodeDef editor)

Make user menu the topmost element

---

test/it/006activityLogTest.js
test/it/surveyTests/surveyTest.js
test/it/utils/surveyBuilder.js

Added warnings to prevent anyone else from using the (somehow broken) test suite created surveys.

Test-created survey: Add warning labels not to use

---

server/modules/user/api/userApi.js

3 seconds is enough to prevent some duplicate requests,
and also to keep showing the user the newest image in all realistic
scenarios.

Shorten profile picture cache to 3 seconds

---

server/db/migration/survey/migrations/sqls/20180814141148-create-record-tables-up.sql

I assume this one omission was a mistake. In general, nullable boolean values cause problems.

Ensure all DB boolean fields are NOT NULL

---

Dockerfile
docker-compose.yml
infra/index.ts
infra/travis_push.sh
server/db/migration/create-migration.sh
server/run_nginx.sh
test/run_docker_tests.sh

- Add Cognito IAM roles so Cognito is usable from ECS.
- Build/push containers in Travis CI, and only deploy them with Pulumi
(don't build them at deploy time).

AWS: Cognito IAM roles, refactor builds

---

core/survey/_survey/surveyDependencies.js
server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob.js

Very simple cleanup of NodeDefsImportJob (that will need in a near future a bigger refactor...).
It reduces the amount of memory used by SurveyDependencies.buildGraph function (using ObjectUtils.setInPath instead of R.assocPath).
It also fixes a bug in the default values import (the parsed expression was wrong).

Node defs import job cleanup

---

core/stringUtils.js
core/validation/_validator/validatorFunctions.js
server/modules/nodeDef/manager/nodeDefManager.js
server/modules/nodeDef/repository/nodeDefRepository.js

This makes sure all identifiers are at most 40 characters so that any prefixes and suffixes in use with Postgres fit in the 63 character (byte) limit of Postgres' identifiers.

NodeDef name changes

---

webapp/loggedin/appHeader/components/userPopupMenu.js
webapp/loggedin/modules/analysis/chain/reducer.js
webapp/loggedin/modules/analysis/step/reducer.js
webapp/loggedin/modules/data/dataVis/dataQuery/reducer.js
webapp/loggedin/modules/home/collectImportReport/reducer.js
webapp/loggedin/modules/home/dashboard/activityLog/reducer.js
webapp/loggedin/modules/home/dashboard/recordsSummary/reducer.js
webapp/loggedin/modules/home/surveyCreate/reducer.js
webapp/loggedin/modules/users/user/reducer.js
webapp/loggedin/modules/users/userInvite/reducer.js
webapp/loggedin/surveyViews/category/reducer.js
webapp/loggedin/surveyViews/nodeDef/reducer.js
webapp/loggedin/surveyViews/record/reducer.js
webapp/loggedin/surveyViews/surveyForm/reducer.js
webapp/loggedin/surveyViews/taxonomy/reducer.js
webapp/loggedin/tableViews/reducer.js
webapp/store/login/actions.js
webapp/store/login/reducer.js
webapp/store/survey/categories/reducer.js
webapp/store/survey/nodeDefs/reducer.js
webapp/store/survey/nodeDefsValidation/reducer.js
webapp/store/survey/status/reducer.js
webapp/store/survey/surveyInfo/reducer.js
webapp/store/survey/taxonomies/reducer.js
webapp/store/system/actions.js
webapp/store/user/actions.js
webapp/store/user/reducer.js

We still have a Dependency cycle 
`export const getSurveyCycleKey = (state) =>
R.pipe(UserState.getUser, User.getPrefSurveyCycle(getSurveyId(state)))(state)`

logout, reset

---

core/i18n/resources/en.js
webapp/app/appModules.js
webapp/components/PanelRight/PanelRight.js
webapp/components/expression/expressionEditorPopup.js
webapp/components/survey/CategorySelector/CategorySelector.js
webapp/components/survey/NodeDefDetails/CodeProps.js
webapp/loggedin/surveyViews/categories/categoriesView.js
webapp/loggedin/surveyViews/category/actions.js
webapp/loggedin/surveyViews/category/categoryView.js
webapp/loggedin/surveyViews/items/itemsTable.js
webapp/loggedin/surveyViews/items/itemsTableHeader.js
webapp/loggedin/surveyViews/items/itemsTableRow.js
webapp/loggedin/surveyViews/items/itemsView.js
webapp/views/App/views/Analysis/Analysis.js

Categories View is always shown in a PanelRight
When adding a new category, a other PanelRight is shown. 
If this works we can apply the same logic to TaxonProps.

NodeDefDetails: show categories manager in PanelRight when editing node def

---

webapp/views/App/views/Analysis/Chain/store/actions/step/useSelect.js

This is not a current issue on the sprint but I noticed that if we are into a step with some calculation opened if we chose another step we had an inconsistency

Select step should reset  calculations

---

core/i18n/resources/en.js
core/survey/nodeDef.js
webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js
webapp/components/survey/NodeDefDetails/FileProps.js
webapp/components/survey/SurveyForm/nodeDefs/nodeDefUIProps.js

Resolves #1126 
- add REQUIRED checkbox
This required is added by the Validation tab when the file is not multiple
- when MULTIPLE true: add minimum and maximum number of items
These fields are added into the Validation tab when the file is multiple
- Max. file size (Mb) (optional. This may be required by Arena Mobile)
Field added into the basic tab
- File type (Image | Video | Audio | Other). This will be required by Arena Mobile.
Field added into the basic tab

add file props

---

core/arena/camelize.js
core/arena/camelizePartial.js
core/arena/index.js
core/arena/internal/_camelizePartial.js
server/db/utils/mergeProps.js
server/db/utils/transformCallback.js
test/unit/tests/006A.camelize.js

Fixes #1266
The fix is small but can have side effects on the whole application.
As far as I have seen, everything seems to work fine.
Since the amount code of camelize is very small, should we create our own A.camelize function that accepts a list of properties to skip? Or should we suggest this change to the developer and open a pull request?! I vote for the 2nd...

Fixed error importing Collect survey categories (do not camelize nested props)

---

webapp/components/form/Dropdown/ItemDialog/itemDialog.scss

align dropdown texts to left in order to improve readability.

---

core/systemError.js
server/modules/user/service/userService.js
server/utils/response.js

Resolves #1382 
Before we sent always 500 as a status code in every error, the idea behind this PR is to be more explicit about what is the nature of the error.
An initial StatusCode dictionary was added but could be better replace this for some library, like this: https://www.npmjs.com/package/http-status-codes.
1.  Now the SystemErrors can have a custom StatusCode
2. This Status Codes are defined in a dictionary
3. And this StatusCode is going to be returned into the error response
4. The first Error that implements a different StatusCode than 500 is 'appErrors.userHasPendingInvitation' which instead of being INTERNAL_SERVER_ERROR should be CONFLICT
Invite a user 2 times and see the statuscode error
Try to have other error and ensure that all still works
The dictionary could be changed

Add 409 as status code when user is already invited

---

core/expressionParser/expression.js
core/expressionParser/helpers/evaluator.js
core/expressionParser/helpers/functionImplementations.js
core/expressionParser/helpers/functions.js
core/i18n/resources/en.js
core/record/recordExpressionParser/memberEval.js
core/record/recordExpressionParser/recordEpressionFunctions.js
core/survey/_survey/surveyDependencies.js
core/survey/_survey/surveyDependencyTypes.js
core/survey/_surveyValidator/nodeDefExpressionsValidator.js
core/survey/nodeDefExpression.js
core/survey/nodeDefExpressionValidator/identifierEval.js
core/survey/nodeDefExpressionValidator/index.js
core/survey/nodeDefExpressionValidator/memberEval.js
core/survey/nodeDefExpressionValidator/nodeDefExpressionValidator.js
test/unit/tests/002recordExpressionParser.test.js
webapp/components/expression/codemirrorArenaExpressionHint.js

Resolves #1402 
The parent() function takes a node as argument and returns the parent entity of the specified node. 
Most of the changes have been applied to:
- nodeDefExpressionValidator: the same logic used to validate the expression is used to find the node definition referenced by the expression itself;
- surveyDependencies: now it uses the nodeDefExpressionValidator to get the node definition referenced by the expression (when the parent function is used, even the parent node definition must be considered).
- RecordExpressionParser internal modules: memberEval.js and identifierEval.js has been simplified a bit.
- SurveyDependencyTypes: it has been introduced to avoid import cycles;
- codemirrorArenaExpressionHint.js: it has been modified to support the use of the parent function in …

NodeDefExpression: added parent() function

---

core/expressionParser/helpers/evaluator.js
core/i18n/resources/en.js
core/record/recordExpressionParser/identifierEval.js
core/record/recordExpressionParser/memberEval.js
core/survey/nodeDefExpressionNativeProperties.js
core/survey/nodeDefExpressionValidator/identifierEval.js
core/survey/nodeDefExpressionValidator/memberEval.js
core/survey/nodeDefExpressionValidator/nodeDefExpressionValidator.js
core/validation/_validator/validatorErrorKeys.js
test/unit/tests/002recordExpressionParser.test.js
test/unit/tests/007nodeDefExpressionValidator.test.js
test/utils/dataTest/dataTest.js
test/utils/dataTest/index.js
test/utils/nodeDefExpressionUtils.js

Resolves #1398
This pull request allows the use of native js object properties and functions (such as String.toLowerCase, Number.toFixed etc) on attribute values.
Unit tests have been created to test the evaluation of expressions accessing native properties.
Also a set of unit tests on the NodeDefExpressionValidator module has been added.
The use of the current node def has been allowed in cases of complex expressions accessing sibling entities.
Also, I've moved the creation of the test survey and record to a separate file.
The check if the current node is being referenced by the expression could be improved, even if it looks quite difficult.
Now, when we are defining an expression for a Default Value (self reference not allowed), expressions like this won't be allowed: plot_id + 1 …

Expressions: allowed use of native object properties

---

core/expressionParser/helpers/evaluator/callEval.js
core/expressionParser/helpers/evaluator/evaluator.js
core/expressionParser/helpers/evaluator/globalIdentifierEval.js
core/expressionParser/helpers/evaluator/index.js
core/record/recordExpressionParser/identifierEval.js
core/survey/nodeDefExpressionValidator/identifierEval.js
test/unit/tests/002recordExpressionParser.test.js
test/unit/tests/007nodeDefExpressionValidator.test.js

Resolves #1369
With this pull request it will be possible to use expressions like String(123), Number('1'), Boolean(attribute_name) etc to convert values into different types.
The bigger change is in the evaluation of the "call" expression; I've splitted the evaluator.js module into several modules, moving the code of the old function "callEval" into a separate file. Now the evaluation of the function name in callEval takes into account the global objects.
Unit tests have been added.

Expressions: allow usage of global objects constructors

---

common/model/db/tables/node/select.js
core/expressionParser/expression.js
core/record/node.js
core/record/recordExpressionParser/identifierEval.js
core/record/recordExpressionValueConverter.js
core/survey/nodeDef.js
core/survey/nodeDefExpressionValidator/identifierEval.js
server/modules/analysis/service/rChain/rFile/system/dfResults.js
server/modules/collectImport/service/collectImport/dataImportJobs/collectAttributeValueExtractor.js
server/modules/record/repository/nodeRepository.js
test/unit/tests/002recordExpressionParser.test.js
test/unit/tests/007nodeDefExpressionValidator.test.js
test/utils/dataTest/dataTest.js
webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCode.js
webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefFile.js
webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxon.js
webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefTaxonInputField.js

Resolves #1128
The changes are in the way an "identifier" is evaluated: if it is a composite attribute value member, than the corresponding value is returned.
I've splitted the valuePropKeys into several objects, depending on the type of attribute (and the use of that constant has been updated accordingly).
Unit tests for expression validator and evaluator have been added.
This pull request changes the way in which the value of a "composite" attribute is returned by the expression (now in this case the value object is returned, instead of a string representation of it).
Accessing members of Date and Time attributes will be allowed in the next pull request.

Expressions: allow use of composite attribute members

---

core/validation/validation.js
test/e2e/tests/validationReport.js

Resolves #1415
I've changed the way the validation is "merged" with a new one; for every field validation inside the validation object, when the validation of a field is valid simply remove it from the final validation object, instead of merging with the old one.
E2E test was already in place, I've only restored the commented one done by @minotogna

Fixed non-relevant nodes validation not cleared

---

test/e2e/tests/_formDesigner/index.js
test/e2e/tests/_record/utils.js
test/e2e/tests/nodeDefReorder.js
test/e2e/tests/surveyFormPreview.js
webapp/components/form/LabelWithTooltip/LabelWithTooltip.js
webapp/components/form/LabelWithTooltip/index.js
webapp/components/survey/NodeDefDetails/AnalysisCodeProps/index.js
webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefEditButtons.js
webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefTableCellHeader.js
webapp/components/survey/SurveyForm/nodeDefs/components/nodeDefTableCellHeader.scss
webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTable.scss
webapp/components/survey/SurveyForm/nodeDefs/nodeDefSwitch.js
webapp/utils/dataTestId/index.js

In node def table header, show the node def edit buttons only on mouse over and show a tooltip with the full label/name if the text is too long and overflows the width of the column.
Necessary because when node def names are long it is quite difficult to find a node definition.

Show node def edit buttons only on mouse over

---

core/record/_record/recordNodesIndex.js
core/survey/nodeDef.js
server/modules/nodeDef/repository/nodeDefRepository.js
server/modules/record/manager/recordManager.js
server/modules/record/repository/nodeRepository.js
server/modules/survey/service/recordCheckJob.js

Improved survey publish speed (RecordCheckJob) by checking records only if node defs default values, applicability or default values have been changed.
Fetch nodes excluding record_uuid improves the speed significantly. This can be done when fetching nodes by record uuid (record uuid is already known and can be associated to the fetched rows after the fetch completes).

Survey publish speed

---

webapp/store/ui/chain/actions/openRStudio.js

Fixed bug: running RStudio code locally fails if Files tab is not active

---

server/modules/survey/service/surveyExport/exportFile.js

Use constant separator in exportFile so you can read zips on windows that are made in UNIX machine.
Tested manually by importing a backup survey zip
Windows 11 Pro
Google Chrome 101.0.4951.67 64bit

[FIX] fix exportFile to work with windows machines too

---

webapp/components/survey/NodeDefsSelector/NodeDefsSelectorAggregate.js

Explorer / aggregate mode: exclude key attributes from measures

---

server/modules/mobile/api/mobileApi.js

please check if passing "backup=true" is needed in mobile (it should not, only survey and node defs "props" are needed, not propsDraft I suppose).

fixed mobile api survey fetch

---

core/i18n/resources/en.js
webapp/components/survey/Surveys/HeaderLeft/HeaderLeft.js

layout adjustments

---

core/survey/nodeDef.js
server/modules/nodeDef/manager/nodeDefManager.js

hiearchy could be broken (still investigating on it) and when survey is read with a broken hierarchy, data import fails or skips nodes

re-calculate node defs hierarchy when survey is loaded

---

core/i18n/resources/en/common.js
webapp/components/Dropzone/Dropzone.js

fixed dropzone invalid file error message

---

core/i18n/resources/en/common.js
webapp/components/buttons/ButtonMenu.js
webapp/components/buttons/ButtonMenu.scss
webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.js
webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/WhispMenuButton.js

Map: added Whisp Earth Map button

---

webapp/components/buttons/ButtonNext.js
webapp/components/buttons/ButtonPrevious.js
webapp/views/App/views/Data/MapView/CoordinateAttributeDataLayer/CoordinateAttributePopUp.scss
webapp/views/App/views/Data/MapView/MapView.js
webapp/views/App/views/Data/MapView/MapView.scss
webapp/views/App/views/Data/MapView/SamplingPointDataLayer/SamplingPointDataItemPopup.js

map: layout adjustments

---

core/survey/_survey/surveyNodeDefs.js
webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js

fixed survey hierarchy items not shown in order

---

webapp/components/expression/expressionVariables.js

Data explorer filter: exclude "this" variable (entity) in basic expression builder

---

webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.scss
webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesList.js
webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesList.scss
webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesSelector.js
webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesSelector.scss
webapp/components/survey/NodeDefsSelector/NodeDefsSelector.js
webapp/components/survey/NodeDefsSelector/NodeDefsSelectorAggregate.js

Survey hiearchy and data explorer: group attributes by parent entity

---

server/modules/survey/service/schemaSummary/schemaSummary.js
test/e2e/tests/surveySchemaSummary.js

Schema summary: added validation_message_LANG columns
